// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/lcs/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "lcs.py",
    "language": "python",
    "title": "LCS (Python)",
    "sourceFile": "src/codeCatalog/lcs/langs/lcs.py",
    "source": "def lcs(X: str, Y: str) -> tuple[int, str]:\n    \"\"\"LCS DP + reconstruct — complete Python reference.\"\"\"\n    m = len(X)\n    n = len(Y)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1):\n        dp[i][0] = 0\n    for j in range(n + 1):\n        dp[0][j] = 0\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if X[i - 1] == Y[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1] + 1\n            else:\n                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])\n    i = m\n    j = n\n    chars: list[str] = []\n    while i > 0 and j > 0:\n        if X[i - 1] == Y[j - 1]:\n            chars.append(X[i - 1])\n            i -= 1\n            j -= 1\n        elif dp[i - 1][j] >= dp[i][j - 1]:\n            i -= 1\n        else:\n            j -= 1\n    return dp[m][n], \"\".join(reversed(chars))\n",
    "sourceHash": "a152446b32fe65dc643f627b5175b5e78d6d0b2d381a09c54eacda44532f7a2d",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 9
        }
      },
      {
        "id": "compareChars",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "takeDiagonal",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "write",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "dpWrite",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "dpFill",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "reconstructStart",
        "range": {
          "startLine": 16,
          "endLine": 17
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "reconstructMove",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "reconstructCompare",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "reconstructUp",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "reconstructLeft",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      }
    ]
  },
  {
    "documentId": "lcs.cpp",
    "language": "cpp",
    "title": "LCS (C++)",
    "sourceFile": "src/codeCatalog/lcs/langs/lcs.cpp",
    "source": "// LCS DP + reconstruct — complete C++ reference.\n#include <algorithm>\n#include <string>\n#include <vector>\n\nstruct LcsResult {\n  int length;\n  std::string sequence;\n};\n\nLcsResult lcs(const std::string& X, const std::string& Y) {\n  const int m = static_cast<int>(X.size());\n  const int n = static_cast<int>(Y.size());\n  std::vector<std::vector<int>> dp(m + 1, std::vector<int>(n + 1, 0));\n  for (int i = 0; i <= m; i++) dp[i][0] = 0;\n  for (int j = 0; j <= n; j++) dp[0][j] = 0;\n  for (int i = 1; i <= m; i++) {\n    for (int j = 1; j <= n; j++) {\n      if (X[i - 1] == Y[j - 1]) {\n        dp[i][j] = dp[i - 1][j - 1] + 1;\n      } else {\n        dp[i][j] = std::max(dp[i - 1][j], dp[i][j - 1]);\n      }\n    }\n  }\n  int i = m;\n  int j = n;\n  std::string chars;\n  while (i > 0 && j > 0) {\n    if (X[i - 1] == Y[j - 1]) {\n      chars.push_back(X[i - 1]);\n      i--;\n      j--;\n    } else if (dp[i - 1][j] >= dp[i][j - 1]) {\n      i--;\n    } else {\n      j--;\n    }\n  }\n  return {dp[m][n], std::string(chars.rbegin(), chars.rend())};\n}\n",
    "sourceHash": "60612cc0cc4c3c8e7bde33813e2aae8a4c2e799aa43051bed172bf665ba3600a",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "compareChars",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "takeDiagonal",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "write",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "dpWrite",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "dpFill",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "reconstructStart",
        "range": {
          "startLine": 26,
          "endLine": 27
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "reconstructMove",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      },
      {
        "id": "reconstructCompare",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      },
      {
        "id": "reconstructUp",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "reconstructLeft",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      }
    ]
  },
  {
    "documentId": "lcs.java",
    "language": "java",
    "title": "LCS (Java)",
    "sourceFile": "src/codeCatalog/lcs/langs/Lcs.java",
    "source": "/** LCS DP + reconstruct — complete Java reference. */\npublic final class Lcs {\n  public record Result(int length, String sequence) {}\n\n  public static Result lcs(String X, String Y) {\n    int m = X.length();\n    int n = Y.length();\n    int[][] dp = new int[m + 1][n + 1];\n    for (int i = 0; i <= m; i++) dp[i][0] = 0;\n    for (int j = 0; j <= n; j++) dp[0][j] = 0;\n    for (int i = 1; i <= m; i++) {\n      for (int j = 1; j <= n; j++) {\n        if (X.charAt(i - 1) == Y.charAt(j - 1)) {\n          dp[i][j] = dp[i - 1][j - 1] + 1;\n        } else {\n          dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);\n        }\n      }\n    }\n    int i = m;\n    int j = n;\n    StringBuilder chars = new StringBuilder();\n    while (i > 0 && j > 0) {\n      if (X.charAt(i - 1) == Y.charAt(j - 1)) {\n        chars.append(X.charAt(i - 1));\n        i--;\n        j--;\n      } else if (dp[i - 1][j] >= dp[i][j - 1]) {\n        i--;\n      } else {\n        j--;\n      }\n    }\n    return new Result(dp[m][n], chars.reverse().toString());\n  }\n}\n",
    "sourceHash": "32982c3c98bbed42b4784c88fe43b846d9e16c5c9a41a8844a60f5133cbadeb2",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 9,
          "endLine": 10
        }
      },
      {
        "id": "compareChars",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "takeDiagonal",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "write",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "dpWrite",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "dpFill",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "reconstructStart",
        "range": {
          "startLine": 20,
          "endLine": 21
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "reconstructMove",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      },
      {
        "id": "reconstructCompare",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      },
      {
        "id": "reconstructUp",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "reconstructLeft",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      }
    ]
  },
  {
    "documentId": "lcs.rs",
    "language": "rust",
    "title": "LCS (Rust)",
    "sourceFile": "src/codeCatalog/lcs/langs/lcs.rs",
    "source": "/// LCS DP + reconstruct — complete Rust reference.\npub fn lcs(x_str: &str, y_str: &str) -> (usize, String) {\n    let x: Vec<char> = x_str.chars().collect();\n    let y: Vec<char> = y_str.chars().collect();\n    let (m, n) = (x.len(), y.len());\n    let mut dp = vec![vec![0usize; n + 1]; m + 1];\n    for i in 0..=m {\n        dp[i][0] = 0;\n    }\n    for j in 0..=n {\n        dp[0][j] = 0;\n    }\n    for i in 1..=m {\n        for j in 1..=n {\n            if x[i - 1] == y[j - 1] {\n                dp[i][j] = dp[i - 1][j - 1] + 1;\n            } else {\n                dp[i][j] = dp[i - 1][j].max(dp[i][j - 1]);\n            }\n        }\n    }\n    let mut i = m;\n    let mut j = n;\n    let mut chars: Vec<char> = Vec::new();\n    while i > 0 && j > 0 {\n        if x[i - 1] == y[j - 1] {\n            chars.push(x[i - 1]);\n            i -= 1;\n            j -= 1;\n        } else if dp[i - 1][j] >= dp[i][j - 1] {\n            i -= 1;\n        } else {\n            j -= 1;\n        }\n    }\n    (dp[m][n], chars.iter().rev().collect())\n}\n",
    "sourceHash": "a72cbac617b2e88855038a2491433f73746264fd4c49d36820ee5f8d50b04d4f",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 12
        }
      },
      {
        "id": "compareChars",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "takeDiagonal",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "write",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "dpWrite",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "dpFill",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "reconstructStart",
        "range": {
          "startLine": 22,
          "endLine": 23
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "reconstructMove",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "reconstructCompare",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "reconstructUp",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "reconstructLeft",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 36,
          "endLine": 36
        }
      }
    ]
  },
  {
    "documentId": "lcs.go",
    "language": "go",
    "title": "LCS (Go)",
    "sourceFile": "src/codeCatalog/lcs/langs/lcs.go",
    "source": "// LCS DP + reconstruct — complete Go reference.\npackage algorithms\n\nimport \"slices\"\n\n// lcs returns the LCS length of X and Y and one longest common subsequence.\nfunc lcs(X, Y string) (int, string) {\n\tm := len(X)\n\tn := len(Y)\n\tdp := make([][]int, m+1)\n\tfor i := range dp {\n\t\tdp[i] = make([]int, n+1)\n\t}\n\tfor i := 0; i <= m; i++ {\n\t\tdp[i][0] = 0\n\t}\n\tfor j := 0; j <= n; j++ {\n\t\tdp[0][j] = 0\n\t}\n\tfor i := 1; i <= m; i++ {\n\t\tfor j := 1; j <= n; j++ {\n\t\t\tif X[i-1] == Y[j-1] {\n\t\t\t\tdp[i][j] = dp[i-1][j-1] + 1\n\t\t\t} else {\n\t\t\t\tdp[i][j] = max(dp[i-1][j], dp[i][j-1])\n\t\t\t}\n\t\t}\n\t}\n\ti := m\n\tj := n\n\tchars := []byte{}\n\tfor i > 0 && j > 0 {\n\t\tif X[i-1] == Y[j-1] {\n\t\t\tchars = append(chars, X[i-1])\n\t\t\ti--\n\t\t\tj--\n\t\t} else if dp[i-1][j] >= dp[i][j-1] {\n\t\t\ti--\n\t\t} else {\n\t\t\tj--\n\t\t}\n\t}\n\tslices.Reverse(chars)\n\treturn dp[m][n], string(chars)\n}\n",
    "sourceHash": "af641555a3d1dfd5d6aa0f025243d40f4b2984f3f6f6912e8998dc3047ab673b",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 14,
          "endLine": 19
        }
      },
      {
        "id": "compareChars",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "takeDiagonal",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "write",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "dpWrite",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "dpFill",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "reconstructStart",
        "range": {
          "startLine": 29,
          "endLine": 30
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      },
      {
        "id": "reconstructMove",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      },
      {
        "id": "reconstructCompare",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      },
      {
        "id": "reconstructUp",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      },
      {
        "id": "reconstructLeft",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 44,
          "endLine": 44
        }
      }
    ]
  }
]

export default docs
