// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/dp1dWrong/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.dp1dWrong.py",
    "language": "python",
    "title": "0-1 背包一维正向反例 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dWrong/langs/knapsack_dp1d_wrong_forward.py",
    "source": "def knapsack_dp1d_wrong_forward(weights: list[int], values: list[int], W: int) -> int:\n    \"\"\"0-1 knapsack 1D WRONG forward update (counterexample) — complete Python reference.\"\"\"\n    dp = [0] * (W + 1)\n    for i in range(len(weights)):\n        wt = weights[i]\n        val = values[i]\n        for w in range(wt, W + 1):\n            dp[w] = max(dp[w], dp[w - wt] + val)\n    return dp[W]\n",
    "sourceHash": "3e65646ef11ab2441f09b27307967ab9956d50e92913cfbd2b49d9776f9fa9f2",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "forward",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dWrong.cpp",
    "language": "cpp",
    "title": "0-1 背包一维正向反例 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dWrong/langs/knapsack_dp1d_wrong_forward.cpp",
    "source": "// 0-1 knapsack 1D WRONG forward update (counterexample) — complete C++17 reference.\n#include <algorithm>\n#include <vector>\n\nlong long knapsackDp1dWrongForward(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    std::vector<long long> dp(W + 1, 0);\n    for (size_t i = 0; i < weights.size(); i++) {\n        int wt = weights[i];\n        long long val = values[i];\n        for (int w = wt; w <= W; w++) {\n            dp[w] = std::max(dp[w], dp[w - wt] + val);\n        }\n    }\n    return dp[W];\n}\n",
    "sourceHash": "3951e6102cf116975a19d4aa62dfb0d28d5d2863594f6a4fc74e4d7b6168dc90",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "forward",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dWrong.java",
    "language": "java",
    "title": "0-1 背包一维正向反例 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dWrong/langs/KnapsackDp1dWrong.java",
    "source": "/** 0-1 knapsack 1D WRONG forward update (counterexample) — complete Java reference. */\npublic final class KnapsackDp1dWrong {\n    public static long knapsackDp1dWrongForward(int[] weights, long[] values, int W) {\n        long[] dp = new long[W + 1];\n        for (int i = 0; i < weights.length; i++) {\n            int wt = weights[i];\n            long val = values[i];\n            for (int w = wt; w <= W; w++) {\n                dp[w] = Math.max(dp[w], dp[w - wt] + val);\n            }\n        }\n        return dp[W];\n    }\n}\n",
    "sourceHash": "9b2dab66f05cbabc238663d895a3f494ab82df9fb4e8dbbc7e4b114a4885a245",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "forward",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dWrong.rs",
    "language": "rust",
    "title": "0-1 背包一维正向反例 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dWrong/langs/knapsack_dp1d_wrong_forward.rs",
    "source": "/// 0-1 knapsack 1D WRONG forward update (counterexample) — complete Rust reference (capacity W is `cap`).\npub fn knapsack_dp1d_wrong_forward(weights: &[usize], values: &[i64], cap: usize) -> i64 {\n    let mut dp = vec![0i64; cap + 1];\n    for i in 0..weights.len() {\n        let wt = weights[i];\n        let val = values[i];\n        for w in wt..=cap {\n            dp[w] = dp[w].max(dp[w - wt] + val);\n        }\n    }\n    dp[cap]\n}\n",
    "sourceHash": "203fb0f733a0b80c98094b59009da958bd88d757b55775cc25302ee70f681b30",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "forward",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dWrong.go",
    "language": "go",
    "title": "0-1 背包一维正向反例 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dWrong/langs/knapsack_dp1d_wrong_forward.go",
    "source": "package algorithms\n\n// knapsackDp1dWrongForward — 0-1 knapsack 1D WRONG forward update (counterexample), complete Go reference.\nfunc knapsackDp1dWrongForward(weights, values []int, W int) int {\n\tdp := make([]int, W+1)\n\tfor i := 0; i < len(weights); i++ {\n\t\twt := weights[i]\n\t\tval := values[i]\n\t\tfor w := wt; w <= W; w++ {\n\t\t\tdp[w] = max(dp[w], dp[w-wt]+val)\n\t\t}\n\t}\n\treturn dp[W]\n}\n",
    "sourceHash": "4bc82ce24f6fd5ed2676d0f1c0248277604553106f4c2c0b9cdc2c1f18f2ba74",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "forward",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      }
    ]
  }
]

export default docs
