// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/dp2d/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.dp2d.py",
    "language": "python",
    "title": "0-1 背包 DP 二维 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/dp2d/langs/knapsack_dp2d.py",
    "source": "def knapsack_dp2d(weights: list[int], values: list[int], W: int) -> tuple[int, list[int]]:\n    \"\"\"0-1 knapsack DP 2D — complete Python reference. Returns (max_value, selected).\"\"\"\n    n = len(weights)\n    dp = [[0] * (W + 1) for _ in range(n + 1)]\n    for i in range(1, n + 1):\n        wt = weights[i - 1]\n        val = values[i - 1]\n        for w in range(W + 1):\n            dp[i][w] = dp[i - 1][w]\n            if w >= wt:\n                take = dp[i - 1][w - wt] + val\n                if take > dp[i][w]:\n                    dp[i][w] = take\n    selected: list[int] = []\n    w = W\n    for i in range(n, 0, -1):\n        if dp[i][w] != dp[i - 1][w]:\n            selected.append(i - 1)\n            w -= weights[i - 1]\n    selected.reverse()\n    return dp[n][W], selected\n",
    "sourceHash": "49750d580a8dad58bd039c41f4ecdd2b699ef39af553d0b0eac834a5e7269675",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "fill",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "takeWrite",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp2d.cpp",
    "language": "cpp",
    "title": "0-1 背包 DP 二维 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/dp2d/langs/knapsack_dp2d.cpp",
    "source": "// 0-1 knapsack DP 2D — complete C++17 reference.\n#include <algorithm>\n#include <utility>\n#include <vector>\n\nstd::pair<long long, std::vector<int>> knapsackDp2d(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    int n = static_cast<int>(weights.size());\n    std::vector<std::vector<long long>> dp(n + 1, std::vector<long long>(W + 1, 0));\n    for (int i = 1; i <= n; i++) {\n        int wt = weights[i - 1];\n        long long val = values[i - 1];\n        for (int w = 0; w <= W; w++) {\n            dp[i][w] = dp[i - 1][w];\n            if (w >= wt) {\n                long long take = dp[i - 1][w - wt] + val;\n                if (take > dp[i][w]) dp[i][w] = take;\n            }\n        }\n    }\n    std::vector<int> selected;\n    int w = W;\n    for (int i = n; i >= 1; i--) {\n        if (dp[i][w] != dp[i - 1][w]) {\n            selected.push_back(i - 1);\n            w -= weights[i - 1];\n        }\n    }\n    std::reverse(selected.begin(), selected.end());\n    return {dp[n][W], selected};\n}\n",
    "sourceHash": "de2d13e825879f60503e00884eb7d4ef2004a2d231db6d4104c9f30a82e39fcb",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "fill",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "takeWrite",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp2d.java",
    "language": "java",
    "title": "0-1 背包 DP 二维 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/dp2d/langs/KnapsackDp2d.java",
    "source": "import java.util.ArrayList;\nimport java.util.Collections;\nimport java.util.List;\n\n/** 0-1 knapsack DP 2D — complete Java reference. */\npublic final class KnapsackDp2d {\n    public record Result(long maxValue, List<Integer> selected) {}\n\n    public static Result knapsackDp2d(int[] weights, long[] values, int W) {\n        int n = weights.length;\n        long[][] dp = new long[n + 1][W + 1];\n        for (int i = 1; i <= n; i++) {\n            int wt = weights[i - 1];\n            long val = values[i - 1];\n            for (int w = 0; w <= W; w++) {\n                dp[i][w] = dp[i - 1][w];\n                if (w >= wt) {\n                    long take = dp[i - 1][w - wt] + val;\n                    if (take > dp[i][w]) dp[i][w] = take;\n                }\n            }\n        }\n        List<Integer> selected = new ArrayList<>();\n        int w = W;\n        for (int i = n; i >= 1; i--) {\n            if (dp[i][w] != dp[i - 1][w]) {\n                selected.add(i - 1);\n                w -= weights[i - 1];\n            }\n        }\n        Collections.reverse(selected);\n        return new Result(dp[n][W], selected);\n    }\n}\n",
    "sourceHash": "3bf39abe1f4e6cdb9465807c363acb7dea0392874329c4bc6fc2bad455b937f6",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "fill",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "takeWrite",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp2d.rs",
    "language": "rust",
    "title": "0-1 背包 DP 二维 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/dp2d/langs/knapsack_dp2d.rs",
    "source": "/// 0-1 knapsack DP 2D — complete Rust reference. Returns (max_value, selected).\npub fn knapsack_dp2d(weights: &[usize], values: &[i64], cap: usize) -> (i64, Vec<usize>) {\n    let n = weights.len();\n    let mut dp = vec![vec![0i64; cap + 1]; n + 1];\n    for i in 1..=n {\n        let wt = weights[i - 1];\n        let val = values[i - 1];\n        for w in 0..=cap {\n            dp[i][w] = dp[i - 1][w];\n            if w >= wt {\n                let take = dp[i - 1][w - wt] + val;\n                if take > dp[i][w] { dp[i][w] = take; }\n            }\n        }\n    }\n    let mut selected: Vec<usize> = Vec::new();\n    let mut w = cap;\n    for i in (1..=n).rev() {\n        if dp[i][w] != dp[i - 1][w] {\n            selected.push(i - 1);\n            w -= weights[i - 1];\n        }\n    }\n    selected.reverse();\n    (dp[n][cap], selected)\n}\n",
    "sourceHash": "8c5a0489542adbc29a5381e4f9f1cce54d3159ea1d608e6a123568156aa49602",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "fill",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "takeWrite",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp2d.go",
    "language": "go",
    "title": "0-1 背包 DP 二维 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/dp2d/langs/knapsack_dp2d.go",
    "source": "package algorithms\n\n// knapsackDp2d — 0-1 knapsack DP 2D, complete Go reference. Returns (maxValue, selected).\nfunc knapsackDp2d(weights, values []int, W int) (int, []int) {\n\tn := len(weights)\n\tdp := make([][]int, n+1)\n\tfor i := range dp {\n\t\tdp[i] = make([]int, W+1)\n\t}\n\tfor i := 1; i <= n; i++ {\n\t\twt := weights[i-1]\n\t\tval := values[i-1]\n\t\tfor w := 0; w <= W; w++ {\n\t\t\tdp[i][w] = dp[i-1][w]\n\t\t\tif w >= wt {\n\t\t\t\ttake := dp[i-1][w-wt] + val\n\t\t\t\tif take > dp[i][w] {\n\t\t\t\t\tdp[i][w] = take\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\tselected := []int{}\n\tw := W\n\tfor i := n; i >= 1; i-- {\n\t\tif dp[i][w] != dp[i-1][w] {\n\t\t\tselected = append(selected, i-1)\n\t\t\tw -= weights[i-1]\n\t\t}\n\t}\n\tfor l, r := 0, len(selected)-1; l < r; l, r = l+1, r-1 {\n\t\tselected[l], selected[r] = selected[r], selected[l]\n\t}\n\treturn dp[n][W], selected\n}\n",
    "sourceHash": "809e1d3a362495f8b61de9a5d04794c536f6359eec83f6baa97737928c99f9ce",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 9
        }
      },
      {
        "id": "fill",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "takeWrite",
        "range": {
          "startLine": 17,
          "endLine": 18
        }
      },
      {
        "id": "reconstruct",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      }
    ]
  }
]

export default docs
