// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/binarySearch/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "binarySearch.py",
    "language": "python",
    "title": "二分查找 · 最左匹配 (Python)",
    "sourceFile": "src/codeCatalog/binarySearch/langs/binary_search.py",
    "source": "def binary_search(a: list[int], target: int) -> int:\n    \"\"\"Binary search — leftmost (lower-bound style) Python reference.\"\"\"\n    lo = 0\n    hi = len(a) - 1\n    candidate = -1\n    while lo <= hi:\n        mid = lo + ((hi - lo) >> 1)\n        if a[mid] == target:\n            candidate = mid\n            hi = mid - 1\n        elif a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return candidate\n",
    "sourceHash": "5fbf7d9f2016a892834c3c87f1a60ba8f278ff1aafdf991ee2bbccfd4d2cbd70",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 5
        }
      },
      {
        "id": "mid",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 8,
          "endLine": 10
        }
      },
      {
        "id": "less",
        "range": {
          "startLine": 11,
          "endLine": 12
        }
      },
      {
        "id": "greater",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "found",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "miss",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  },
  {
    "documentId": "binarySearch.cpp",
    "language": "cpp",
    "title": "二分查找 · 最左匹配 (C++)",
    "sourceFile": "src/codeCatalog/binarySearch/langs/binary_search.cpp",
    "source": "// Binary search — leftmost (lower-bound style) C++17 reference.\n#include <vector>\n\nint binarySearch(const std::vector<int>& a, int target) {\n    int lo = 0;\n    int hi = static_cast<int>(a.size()) - 1;\n    int candidate = -1;\n    while (lo <= hi) {\n        int mid = lo + ((hi - lo) >> 1);\n        if (a[mid] == target) {\n            candidate = mid;\n            hi = mid - 1;\n        } else if (a[mid] < target) {\n            lo = mid + 1;\n        } else {\n            hi = mid - 1;\n        }\n    }\n    return candidate;\n}\n",
    "sourceHash": "a9fde08377382c55c5f7475a1fd9ec0aec531d39dcf8eb1f1c10928fc3a2e19c",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 7
        }
      },
      {
        "id": "mid",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 10,
          "endLine": 12
        }
      },
      {
        "id": "less",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "greater",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "found",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "miss",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "binarySearch.java",
    "language": "java",
    "title": "二分查找 · 最左匹配 (Java)",
    "sourceFile": "src/codeCatalog/binarySearch/langs/BinarySearch.java",
    "source": "/** Binary search — leftmost (lower-bound style) Java reference. */\npublic final class BinarySearch {\n    public static int binarySearch(int[] a, int target) {\n        int lo = 0;\n        int hi = a.length - 1;\n        int candidate = -1;\n        while (lo <= hi) {\n            int mid = lo + ((hi - lo) >> 1);\n            if (a[mid] == target) {\n                candidate = mid;\n                hi = mid - 1;\n            } else if (a[mid] < target) {\n                lo = mid + 1;\n            } else {\n                hi = mid - 1;\n            }\n        }\n        return candidate;\n    }\n}\n",
    "sourceHash": "8aa6a5a49682d2e4e3b584907d03f7bc081f83647ceb2a80359bb68c30086d33",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 6
        }
      },
      {
        "id": "mid",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 9,
          "endLine": 11
        }
      },
      {
        "id": "less",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "greater",
        "range": {
          "startLine": 14,
          "endLine": 15
        }
      },
      {
        "id": "found",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "miss",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      }
    ]
  },
  {
    "documentId": "binarySearch.rs",
    "language": "rust",
    "title": "二分查找 · 最左匹配 (Rust)",
    "sourceFile": "src/codeCatalog/binarySearch/langs/binary_search.rs",
    "source": "/// Binary search — leftmost (lower-bound style) Rust reference (signed bounds, -1 = not found).\npub fn binary_search(a: &[i64], target: i64) -> isize {\n    let mut lo: isize = 0;\n    let mut hi: isize = a.len() as isize - 1;\n    let mut candidate: isize = -1;\n    while lo <= hi {\n        let mid = lo + ((hi - lo) >> 1);\n        if a[mid as usize] == target {\n            candidate = mid;\n            hi = mid - 1;\n        } else if a[mid as usize] < target {\n            lo = mid + 1;\n        } else {\n            hi = mid - 1;\n        }\n    }\n    candidate\n}\n",
    "sourceHash": "97d72b932b39decdbdcdf6fe3c69d59e5ee155c5849b0501e22999ccec224e3e",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 5
        }
      },
      {
        "id": "mid",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 8,
          "endLine": 10
        }
      },
      {
        "id": "less",
        "range": {
          "startLine": 11,
          "endLine": 12
        }
      },
      {
        "id": "greater",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "found",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "miss",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      }
    ]
  },
  {
    "documentId": "binarySearch.go",
    "language": "go",
    "title": "二分查找 · 最左匹配 (Go)",
    "sourceFile": "src/codeCatalog/binarySearch/langs/binary_search.go",
    "source": "package algorithms\n\n// binarySearch — leftmost (lower-bound style) Go reference.\nfunc binarySearch(a []int, target int) int {\n\tlo := 0\n\thi := len(a) - 1\n\tcandidate := -1\n\tfor lo <= hi {\n\t\tmid := lo + ((hi - lo) >> 1)\n\t\tif a[mid] == target {\n\t\t\tcandidate = mid\n\t\t\thi = mid - 1\n\t\t} else if a[mid] < target {\n\t\t\tlo = mid + 1\n\t\t} else {\n\t\t\thi = mid - 1\n\t\t}\n\t}\n\treturn candidate\n}\n",
    "sourceHash": "2945f20c556a5b802d7f18bd5e2451e3559d6b89c55f9c64a5821caa884bf552",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 7
        }
      },
      {
        "id": "mid",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 10,
          "endLine": 12
        }
      },
      {
        "id": "less",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "greater",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "found",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "miss",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  }
]

export default docs
