// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/floyd/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "floyd.py",
    "language": "python",
    "title": "Floyd-Warshall (Python)",
    "sourceFile": "src/codeCatalog/floyd/langs/floyd.py",
    "source": "INF = float(\"inf\")  # missing edge\n\n\ndef floyd(dist: list[list[float]]) -> list[list[float]]:\n    \"\"\"Floyd-Warshall — complete Python reference.\"\"\"\n    n = len(dist)\n    d = [row[:] for row in dist]\n    for k in range(n):\n        for i in range(n):\n            for j in range(n):\n                if d[i][k] + d[k][j] < d[i][j]:\n                    d[i][j] = d[i][k] + d[k][j]\n    return d\n",
    "sourceHash": "2ac069f6920b1e84576b3fa6de854cc7f09f1b886abb1bfa81218d3563b39d9f",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "kLoop",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      }
    ]
  },
  {
    "documentId": "floyd.cpp",
    "language": "cpp",
    "title": "Floyd-Warshall (C++)",
    "sourceFile": "src/codeCatalog/floyd/langs/floyd.cpp",
    "source": "// Floyd-Warshall — complete C++ reference.\n#include <limits>\n#include <vector>\n\nconst double INF = std::numeric_limits<double>::infinity();  // missing edge\n\nstd::vector<std::vector<double>> floyd(const std::vector<std::vector<double>>& dist) {\n  const size_t n = dist.size();\n  std::vector<std::vector<double>> d = dist;\n  for (size_t k = 0; k < n; k++) {\n    for (size_t i = 0; i < n; i++) {\n      for (size_t j = 0; j < n; j++) {\n        if (d[i][k] + d[k][j] < d[i][j]) {\n          d[i][j] = d[i][k] + d[k][j];\n        }\n      }\n    }\n  }\n  return d;\n}\n",
    "sourceHash": "3f2bb4f9a677ecfc0976d2c909b71c4627b2f6030d56e45d79f4c3aefc481b69",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "kLoop",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "floyd.java",
    "language": "java",
    "title": "Floyd-Warshall (Java)",
    "sourceFile": "src/codeCatalog/floyd/langs/Floyd.java",
    "source": "/** Floyd-Warshall — complete Java reference. */\npublic final class Floyd {\n  public static final double INF = Double.POSITIVE_INFINITY; // missing edge\n\n  public static double[][] floyd(double[][] dist) {\n    int n = dist.length;\n    double[][] d = new double[n][];\n    for (int r = 0; r < n; r++) {\n      d[r] = dist[r].clone();\n    }\n    for (int k = 0; k < n; k++) {\n      for (int i = 0; i < n; i++) {\n        for (int j = 0; j < n; j++) {\n          if (d[i][k] + d[k][j] < d[i][j]) {\n            d[i][j] = d[i][k] + d[k][j];\n          }\n        }\n      }\n    }\n    return d;\n  }\n}\n",
    "sourceHash": "2ebe7ed75f45fd5c079ccc8cca2afc7d906f6d276b3f3635694bc40e6dbed367",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 10
        }
      },
      {
        "id": "kLoop",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "floyd.rs",
    "language": "rust",
    "title": "Floyd-Warshall (Rust)",
    "sourceFile": "src/codeCatalog/floyd/langs/floyd.rs",
    "source": "/// Floyd-Warshall — complete Rust reference.\npub const INF: f64 = f64::INFINITY; // missing edge\n\npub fn floyd(dist: &[Vec<f64>]) -> Vec<Vec<f64>> {\n    let n = dist.len();\n    let mut d: Vec<Vec<f64>> = dist.to_vec();\n    for k in 0..n {\n        for i in 0..n {\n            for j in 0..n {\n                if d[i][k] + d[k][j] < d[i][j] {\n                    d[i][j] = d[i][k] + d[k][j];\n                }\n            }\n        }\n    }\n    d\n}\n",
    "sourceHash": "7d64fc3a84f1ea8227f634d195663bae858024d73b06e4b1e5386c11fac048ea",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "kLoop",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      }
    ]
  },
  {
    "documentId": "floyd.go",
    "language": "go",
    "title": "Floyd-Warshall (Go)",
    "sourceFile": "src/codeCatalog/floyd/langs/floyd.go",
    "source": "// Floyd-Warshall — complete Go reference.\npackage algorithms\n\nimport \"math\"\n\n// INF marks a missing edge.\nvar INF = math.Inf(1)\n\n// floyd returns the all-pairs shortest-path matrix for dist (INF = no edge).\nfunc floyd(dist [][]float64) [][]float64 {\n\tn := len(dist)\n\td := make([][]float64, n)\n\tfor r := range dist {\n\t\td[r] = append([]float64(nil), dist[r]...)\n\t}\n\tfor k := 0; k < n; k++ {\n\t\tfor i := 0; i < n; i++ {\n\t\t\tfor j := 0; j < n; j++ {\n\t\t\t\tif d[i][k]+d[k][j] < d[i][j] {\n\t\t\t\t\td[i][j] = d[i][k] + d[k][j]\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\treturn d\n}\n",
    "sourceHash": "debae525f5440743fb0844694d7c3a3b8c20a7719a7ef9dca42842169aca6164",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 12,
          "endLine": 15
        }
      },
      {
        "id": "kLoop",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      }
    ]
  }
]

export default docs
