// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/mergeSort/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "mergeSort.py",
    "language": "python",
    "title": "归并排序 (Python)",
    "sourceFile": "src/codeCatalog/mergeSort/langs/merge_sort.py",
    "source": "def merge_sort(a: list[int]) -> list[int]:\n    \"\"\"Merge sort — complete Python reference (in-place merge, L/R/k).\"\"\"\n    arr = list(a)\n    sort(arr, 0, len(arr) - 1)\n    return arr\n\n\ndef sort(a: list[int], L: int, R: int) -> None:\n    if L >= R:\n        return\n    mid = (L + R) // 2\n    sort(a, L, mid)\n    sort(a, mid + 1, R)\n    merge(a, L, mid, R)\n\n\ndef merge(a: list[int], L: int, mid: int, R: int) -> None:\n    left = a[L:mid + 1]\n    right = a[mid + 1:R + 1]\n    i = 0\n    j = 0\n    k = L\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            a[k] = left[i]\n            i += 1\n            k += 1\n        else:\n            a[k] = right[j]\n            j += 1\n            k += 1\n    while i < len(left):\n        a[k] = left[i]\n        i += 1\n        k += 1\n    while j < len(right):\n        a[k] = right[j]\n        j += 1\n        k += 1\n",
    "sourceHash": "d8c6d6e6e89a94c77e3f7dfb0e3f45ba61910264644059c93e86e0d9f65c0fb9",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 9,
          "endLine": 10
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "mergeSlice",
        "range": {
          "startLine": 18,
          "endLine": 19
        }
      },
      {
        "id": "mergeCompare",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "mergeWriteLeft",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "mergeWriteRight",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "mergeCopyLeft",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "mergeCopyRight",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      }
    ]
  },
  {
    "documentId": "mergeSort.cpp",
    "language": "cpp",
    "title": "归并排序 (C++)",
    "sourceFile": "src/codeCatalog/mergeSort/langs/merge_sort.cpp",
    "source": "// Merge sort — complete C++17 reference (in-place merge, L/R/k).\n#include <vector>\n\nvoid sortRange(std::vector<int>& a, int L, int R);\nvoid mergeRange(std::vector<int>& a, int L, int mid, int R);\n\nstd::vector<int> mergeSort(std::vector<int> arr) {\n    sortRange(arr, 0, static_cast<int>(arr.size()) - 1);\n    return arr;\n}\n\nvoid sortRange(std::vector<int>& a, int L, int R) {\n    if (L >= R) return;\n    int mid = (L + R) / 2;\n    sortRange(a, L, mid);\n    sortRange(a, mid + 1, R);\n    mergeRange(a, L, mid, R);\n}\n\nvoid mergeRange(std::vector<int>& a, int L, int mid, int R) {\n    std::vector<int> left(a.begin() + L, a.begin() + mid + 1);\n    std::vector<int> right(a.begin() + mid + 1, a.begin() + R + 1);\n    int i = 0, j = 0, k = L;\n    while (i < static_cast<int>(left.size()) && j < static_cast<int>(right.size())) {\n        if (left[i] <= right[j]) {\n            a[k] = left[i];\n            i++;\n            k++;\n        } else {\n            a[k] = right[j];\n            j++;\n            k++;\n        }\n    }\n    while (i < static_cast<int>(left.size())) {\n        a[k] = left[i];\n        i++;\n        k++;\n    }\n    while (j < static_cast<int>(right.size())) {\n        a[k] = right[j];\n        j++;\n        k++;\n    }\n}\n",
    "sourceHash": "a9d6b3ac08c5be6ce377345da8cee8dd172bba43929960c20168773866944952",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "mergeSlice",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "mergeCompare",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "mergeWriteLeft",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "mergeWriteRight",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "mergeCopyLeft",
        "range": {
          "startLine": 36,
          "endLine": 36
        }
      },
      {
        "id": "mergeCopyRight",
        "range": {
          "startLine": 41,
          "endLine": 41
        }
      }
    ]
  },
  {
    "documentId": "mergeSort.java",
    "language": "java",
    "title": "归并排序 (Java)",
    "sourceFile": "src/codeCatalog/mergeSort/langs/MergeSort.java",
    "source": "import java.util.Arrays;\n\n/** Merge sort — complete Java reference (in-place merge, L/R/k). */\npublic final class MergeSort {\n    public static int[] mergeSort(int[] a) {\n        int[] arr = a.clone();\n        sort(arr, 0, arr.length - 1);\n        return arr;\n    }\n\n    private static void sort(int[] a, int L, int R) {\n        if (L >= R) return;\n        int mid = (L + R) / 2;\n        sort(a, L, mid);\n        sort(a, mid + 1, R);\n        merge(a, L, mid, R);\n    }\n\n    private static void merge(int[] a, int L, int mid, int R) {\n        int[] left = Arrays.copyOfRange(a, L, mid + 1);\n        int[] right = Arrays.copyOfRange(a, mid + 1, R + 1);\n        int i = 0, j = 0, k = L;\n        while (i < left.length && j < right.length) {\n            if (left[i] <= right[j]) {\n                a[k] = left[i];\n                i++;\n                k++;\n            } else {\n                a[k] = right[j];\n                j++;\n                k++;\n            }\n        }\n        while (i < left.length) {\n            a[k] = left[i];\n            i++;\n            k++;\n        }\n        while (j < right.length) {\n            a[k] = right[j];\n            j++;\n            k++;\n        }\n    }\n}\n",
    "sourceHash": "35bdefc52cabc5af73dbced04df1463abc3fcc8908cdac505bbe740037b5e1db",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 14,
          "endLine": 15
        }
      },
      {
        "id": "mergeSlice",
        "range": {
          "startLine": 20,
          "endLine": 21
        }
      },
      {
        "id": "mergeCompare",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "mergeWriteLeft",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "mergeWriteRight",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "mergeCopyLeft",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "mergeCopyRight",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      }
    ]
  },
  {
    "documentId": "mergeSort.rs",
    "language": "rust",
    "title": "归并排序 (Rust)",
    "sourceFile": "src/codeCatalog/mergeSort/langs/merge_sort.rs",
    "source": "/// Merge sort — complete Rust reference (in-place merge, lo/hi/k).\npub fn merge_sort(a: &[i64]) -> Vec<i64> {\n    let mut arr = a.to_vec();\n    let hi = arr.len() as isize - 1;\n    sort(&mut arr, 0, hi);\n    arr\n}\n\nfn sort(a: &mut [i64], lo: isize, hi: isize) {\n    if lo >= hi {\n        return;\n    }\n    let mid = (lo + hi) / 2;\n    sort(a, lo, mid);\n    sort(a, mid + 1, hi);\n    merge(a, lo as usize, mid as usize, hi as usize);\n}\n\nfn merge(a: &mut [i64], lo: usize, mid: usize, hi: usize) {\n    let left = a[lo..mid + 1].to_vec();\n    let right = a[mid + 1..hi + 1].to_vec();\n    let (mut i, mut j, mut k) = (0, 0, lo);\n    while i < left.len() && j < right.len() {\n        if left[i] <= right[j] {\n            a[k] = left[i];\n            i += 1;\n            k += 1;\n        } else {\n            a[k] = right[j];\n            j += 1;\n            k += 1;\n        }\n    }\n    while i < left.len() {\n        a[k] = left[i];\n        i += 1;\n        k += 1;\n    }\n    while j < right.len() {\n        a[k] = right[j];\n        j += 1;\n        k += 1;\n    }\n}\n",
    "sourceHash": "6cd8597b16deeb9de9c56b1f799577340fd1fb5277ca80c198587e06528fef85",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 10,
          "endLine": 11
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 14,
          "endLine": 15
        }
      },
      {
        "id": "mergeSlice",
        "range": {
          "startLine": 20,
          "endLine": 21
        }
      },
      {
        "id": "mergeCompare",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "mergeWriteLeft",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "mergeWriteRight",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "mergeCopyLeft",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "mergeCopyRight",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      }
    ]
  },
  {
    "documentId": "mergeSort.go",
    "language": "go",
    "title": "归并排序 (Go)",
    "sourceFile": "src/codeCatalog/mergeSort/langs/merge_sort.go",
    "source": "package algorithms\n\n// mergeSort — complete Go reference (in-place merge, L/R/k).\nfunc mergeSort(a []int) []int {\n\tarr := append([]int(nil), a...)\n\tsortRange(arr, 0, len(arr)-1)\n\treturn arr\n}\n\nfunc sortRange(a []int, L, R int) {\n\tif L >= R {\n\t\treturn\n\t}\n\tmid := (L + R) / 2\n\tsortRange(a, L, mid)\n\tsortRange(a, mid+1, R)\n\tmergeRange(a, L, mid, R)\n}\n\nfunc mergeRange(a []int, L, mid, R int) {\n\tleft := append([]int(nil), a[L:mid+1]...)\n\tright := append([]int(nil), a[mid+1:R+1]...)\n\ti, j, k := 0, 0, L\n\tfor i < len(left) && j < len(right) {\n\t\tif left[i] <= right[j] {\n\t\t\ta[k] = left[i]\n\t\t\ti++\n\t\t\tk++\n\t\t} else {\n\t\t\ta[k] = right[j]\n\t\t\tj++\n\t\t\tk++\n\t\t}\n\t}\n\tfor i < len(left) {\n\t\ta[k] = left[i]\n\t\ti++\n\t\tk++\n\t}\n\tfor j < len(right) {\n\t\ta[k] = right[j]\n\t\tj++\n\t\tk++\n\t}\n}\n",
    "sourceHash": "10a270b6b04771032bc696620ffc5517277451ed21bf9ab5d27494d94825a546",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 11,
          "endLine": 12
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "mergeSlice",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "mergeCompare",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "mergeWriteLeft",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "mergeWriteRight",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "mergeCopyLeft",
        "range": {
          "startLine": 36,
          "endLine": 36
        }
      },
      {
        "id": "mergeCopyRight",
        "range": {
          "startLine": 41,
          "endLine": 41
        }
      }
    ]
  }
]

export default docs
