// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/matrixChain/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "matrixChain.py",
    "language": "python",
    "title": "矩阵链乘 (Python)",
    "sourceFile": "src/codeCatalog/matrixChain/langs/matrix_chain.py",
    "source": "def matrix_chain_order(dims: list[int]) -> tuple[int, list[list[int]]]:\n    \"\"\"Matrix-chain order DP — complete Python reference. Returns (cost, split).\"\"\"\n    n = len(dims) - 1\n    dp: list[list[float]] = [[0] * n for _ in range(n)]\n    split = [[0] * n for _ in range(n)]\n    for length in range(2, n + 1):\n        for i in range(n - length + 1):\n            j = i + length - 1\n            dp[i][j] = float(\"inf\")\n            for k in range(i, j):\n                cost = dp[i][k] + dp[k + 1][j] + dims[i] * dims[k + 1] * dims[j + 1]\n                if cost < dp[i][j]:\n                    dp[i][j] = cost\n                    split[i][j] = k\n    return int(dp[0][n - 1]), split\n",
    "sourceHash": "eb69e9bbc6c79496794d32e4de4d1a9bde7417aa3ed23ee248eaf19d4dec8321",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 5
        }
      },
      {
        "id": "lenLoop",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "trySplit",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "cost",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  },
  {
    "documentId": "matrixChain.cpp",
    "language": "cpp",
    "title": "矩阵链乘 (C++)",
    "sourceFile": "src/codeCatalog/matrixChain/langs/matrix_chain.cpp",
    "source": "// Matrix-chain order DP — complete C++17 reference.\n#include <climits>\n#include <utility>\n#include <vector>\n\nstd::pair<long long, std::vector<std::vector<int>>> matrixChainOrder(const std::vector<long long>& dims) {\n    int n = static_cast<int>(dims.size()) - 1;\n    std::vector<std::vector<long long>> dp(n, std::vector<long long>(n, 0));\n    std::vector<std::vector<int>> split(n, std::vector<int>(n, 0));\n    for (int len = 2; len <= n; len++) {\n        for (int i = 0; i <= n - len; i++) {\n            int j = i + len - 1;\n            dp[i][j] = LLONG_MAX;\n            for (int k = i; k < j; k++) {\n                long long cost = dp[i][k] + dp[k + 1][j] + dims[i] * dims[k + 1] * dims[j + 1];\n                if (cost < dp[i][j]) {\n                    dp[i][j] = cost;\n                    split[i][j] = k;\n                }\n            }\n        }\n    }\n    return {dp[0][n - 1], split};\n}\n",
    "sourceHash": "231274168d195b76c74fa270bec00201379951a22949470319c3731205cdf161",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 8,
          "endLine": 9
        }
      },
      {
        "id": "lenLoop",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "trySplit",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "cost",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      }
    ]
  },
  {
    "documentId": "matrixChain.java",
    "language": "java",
    "title": "矩阵链乘 (Java)",
    "sourceFile": "src/codeCatalog/matrixChain/langs/MatrixChain.java",
    "source": "/** Matrix-chain order DP — complete Java reference. */\npublic final class MatrixChain {\n    public record Result(long cost, int[][] split) {}\n\n    public static Result matrixChainOrder(long[] dims) {\n        int n = dims.length - 1;\n        long[][] dp = new long[n][n];\n        int[][] split = new int[n][n];\n        for (int len = 2; len <= n; len++) {\n            for (int i = 0; i <= n - len; i++) {\n                int j = i + len - 1;\n                dp[i][j] = Long.MAX_VALUE;\n                for (int k = i; k < j; k++) {\n                    long cost = dp[i][k] + dp[k + 1][j] + dims[i] * dims[k + 1] * dims[j + 1];\n                    if (cost < dp[i][j]) {\n                        dp[i][j] = cost;\n                        split[i][j] = k;\n                    }\n                }\n            }\n        }\n        return new Result(dp[0][n - 1], split);\n    }\n}\n",
    "sourceHash": "5de273c4875a2a7313b8a8b751b13824496aee97321d935e28a311de06bbe744",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 8
        }
      },
      {
        "id": "lenLoop",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "trySplit",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "cost",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      }
    ]
  },
  {
    "documentId": "matrixChain.rs",
    "language": "rust",
    "title": "矩阵链乘 (Rust)",
    "sourceFile": "src/codeCatalog/matrixChain/langs/matrix_chain.rs",
    "source": "/// Matrix-chain order DP — complete Rust reference. Returns (cost, split).\npub fn matrix_chain_order(dims: &[i64]) -> (i64, Vec<Vec<usize>>) {\n    let n = dims.len() - 1;\n    let mut dp = vec![vec![0i64; n]; n];\n    let mut split = vec![vec![0usize; n]; n];\n    for len in 2..=n {\n        for i in 0..=n - len {\n            let j = i + len - 1;\n            dp[i][j] = i64::MAX;\n            for k in i..j {\n                let cost = dp[i][k] + dp[k + 1][j] + dims[i] * dims[k + 1] * dims[j + 1];\n                if cost < dp[i][j] {\n                    dp[i][j] = cost;\n                    split[i][j] = k;\n                }\n            }\n        }\n    }\n    (dp[0][n - 1], split)\n}\n",
    "sourceHash": "72733bb810f8ea60e28233da1818e7a91e2b5f661c1bf43d6b59399344686a7f",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 5
        }
      },
      {
        "id": "lenLoop",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "trySplit",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "cost",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "matrixChain.go",
    "language": "go",
    "title": "矩阵链乘 (Go)",
    "sourceFile": "src/codeCatalog/matrixChain/langs/matrix_chain.go",
    "source": "package algorithms\n\nimport \"math\"\n\n// matrixChainOrder — matrix-chain order DP, complete Go reference. Returns (cost, split).\nfunc matrixChainOrder(dims []int) (int, [][]int) {\n\tn := len(dims) - 1\n\tdp := make([][]int, n)\n\tsplit := make([][]int, n)\n\tfor i := range dp {\n\t\tdp[i], split[i] = make([]int, n), make([]int, n)\n\t}\n\tfor length := 2; length <= n; length++ {\n\t\tfor i := 0; i <= n-length; i++ {\n\t\t\tj := i + length - 1\n\t\t\tdp[i][j] = math.MaxInt\n\t\t\tfor k := i; k < j; k++ {\n\t\t\t\tcost := dp[i][k] + dp[k+1][j] + dims[i]*dims[k+1]*dims[j+1]\n\t\t\t\tif cost < dp[i][j] {\n\t\t\t\t\tdp[i][j] = cost\n\t\t\t\t\tsplit[i][j] = k\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n\treturn dp[0][n-1], split\n}\n",
    "sourceHash": "7ef74ac3db050a4fd7efa366e6e20e75bab75e22209ccdc999c70ee8f10b6910",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 8,
          "endLine": 9
        }
      },
      {
        "id": "lenLoop",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "trySplit",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "cost",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  }
]

export default docs
