// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/quickSort/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "quickSort.py",
    "language": "python",
    "title": "快速排序 (Python)",
    "sourceFile": "src/codeCatalog/quickSort/langs/quick_sort.py",
    "source": "def quick_sort(a: list[int]) -> list[int]:\n    \"\"\"Quick sort (Lomuto, i = L-1 style) — Python reference aligned with the trace.\"\"\"\n    arr = list(a)\n    qs(arr, 0, len(arr) - 1)\n    return arr\n\n\ndef qs(arr: list[int], L: int, R: int) -> None:\n    if L >= R:\n        return\n    p = partition(arr, L, R)\n    qs(arr, L, p - 1)\n    qs(arr, p + 1, R)\n\n\ndef partition(arr: list[int], L: int, R: int) -> int:\n    pivot = arr[R]\n    i = L - 1\n    for j in range(L, R):\n        if arr[j] <= pivot:\n            i += 1\n            arr[i], arr[j] = arr[j], arr[i]\n    p = i + 1\n    arr[p], arr[R] = arr[R], arr[p]\n    return p\n",
    "sourceHash": "3247ce973603e4917cb4d436acf93ecea761e3ba509ff6fbee9d3ac0f39d0a5e",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "baseCase",
        "range": {
          "startLine": 9,
          "endLine": 10
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 11,
          "endLine": 13
        }
      },
      {
        "id": "partition",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "loopSwap",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "pivotPlace",
        "range": {
          "startLine": 23,
          "endLine": 24
        }
      }
    ]
  },
  {
    "documentId": "quickSort.cpp",
    "language": "cpp",
    "title": "快速排序 (C++)",
    "sourceFile": "src/codeCatalog/quickSort/langs/quick_sort.cpp",
    "source": "// Quick sort (Lomuto, i = L-1 style) — C++17 reference aligned with the trace.\n#include <utility>\n#include <vector>\n\nvoid qs(std::vector<int>& arr, int L, int R);\nint partition(std::vector<int>& arr, int L, int R);\n\nstd::vector<int> quickSort(std::vector<int> arr) {\n    qs(arr, 0, static_cast<int>(arr.size()) - 1);\n    return arr;\n}\n\nvoid qs(std::vector<int>& arr, int L, int R) {\n    if (L >= R) return;\n    int p = partition(arr, L, R);\n    qs(arr, L, p - 1);\n    qs(arr, p + 1, R);\n}\n\nint partition(std::vector<int>& arr, int L, int R) {\n    int pivot = arr[R];\n    int i = L - 1;\n    for (int j = L; j < R; j++) {\n        if (arr[j] <= pivot) {\n            i++;\n            std::swap(arr[i], arr[j]);\n        }\n    }\n    int p = i + 1;\n    std::swap(arr[p], arr[R]);\n    return p;\n}\n",
    "sourceHash": "850de096bf1ba972324ea91fded564611d44b1b571ea3e72fecb649915a9c0b2",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "baseCase",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 15,
          "endLine": 17
        }
      },
      {
        "id": "partition",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "loopSwap",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      },
      {
        "id": "pivotPlace",
        "range": {
          "startLine": 29,
          "endLine": 30
        }
      }
    ]
  },
  {
    "documentId": "quickSort.java",
    "language": "java",
    "title": "快速排序 (Java)",
    "sourceFile": "src/codeCatalog/quickSort/langs/QuickSort.java",
    "source": "/** Quick sort (Lomuto, i = L-1 style) — Java reference aligned with the trace. */\npublic final class QuickSort {\n    public static int[] quickSort(int[] a) {\n        int[] arr = a.clone();\n        qs(arr, 0, arr.length - 1);\n        return arr;\n    }\n\n    private static void qs(int[] arr, int L, int R) {\n        if (L >= R) return;\n        int p = partition(arr, L, R);\n        qs(arr, L, p - 1);\n        qs(arr, p + 1, R);\n    }\n\n    private static int partition(int[] arr, int L, int R) {\n        int pivot = arr[R];\n        int i = L - 1;\n        for (int j = L; j < R; j++) {\n            if (arr[j] <= pivot) {\n                i++;\n                int t = arr[i]; arr[i] = arr[j]; arr[j] = t;\n            }\n        }\n        int p = i + 1;\n        int t = arr[p]; arr[p] = arr[R]; arr[R] = t;\n        return p;\n    }\n}\n",
    "sourceHash": "51463abd9145813d25b8e1422af4a321a280722e72741ea38b225e7abc447aa1",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "baseCase",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 11,
          "endLine": 13
        }
      },
      {
        "id": "partition",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "loopSwap",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "pivotPlace",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      }
    ]
  },
  {
    "documentId": "quickSort.rs",
    "language": "rust",
    "title": "快速排序 (Rust)",
    "sourceFile": "src/codeCatalog/quickSort/langs/quick_sort.rs",
    "source": "/// Quick sort (Lomuto, i = lo-1 style) — Rust reference aligned with the trace.\npub fn quick_sort(a: &[i64]) -> Vec<i64> {\n    let mut arr = a.to_vec();\n    let hi = arr.len() as isize - 1;\n    qs(&mut arr, 0, hi);\n    arr\n}\n\nfn qs(arr: &mut [i64], lo: isize, hi: isize) {\n    if lo >= hi {\n        return;\n    }\n    let p = partition(arr, lo, hi);\n    qs(arr, lo, p - 1);\n    qs(arr, p + 1, hi);\n}\n\nfn partition(arr: &mut [i64], lo: isize, hi: isize) -> isize {\n    let pivot = arr[hi as usize];\n    let mut i = lo - 1;\n    for j in lo..hi {\n        if arr[j as usize] <= pivot {\n            i += 1;\n            arr.swap(i as usize, j as usize);\n        }\n    }\n    let p = i + 1;\n    arr.swap(p as usize, hi as usize);\n    p\n}\n",
    "sourceHash": "74679da15b66128042865bd91d45056d986aba0d8630cbc1790b78d9fb6c5e97",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "baseCase",
        "range": {
          "startLine": 10,
          "endLine": 11
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 13,
          "endLine": 15
        }
      },
      {
        "id": "partition",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "loopSwap",
        "range": {
          "startLine": 23,
          "endLine": 24
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 23,
          "endLine": 24
        }
      },
      {
        "id": "pivotPlace",
        "range": {
          "startLine": 27,
          "endLine": 28
        }
      }
    ]
  },
  {
    "documentId": "quickSort.go",
    "language": "go",
    "title": "快速排序 (Go)",
    "sourceFile": "src/codeCatalog/quickSort/langs/quick_sort.go",
    "source": "package algorithms\n\n// quickSort (Lomuto, i = L-1 style) — Go reference aligned with the trace.\nfunc quickSort(a []int) []int {\n\tarr := append([]int(nil), a...)\n\tqs(arr, 0, len(arr)-1)\n\treturn arr\n}\n\nfunc qs(arr []int, L, R int) {\n\tif L >= R {\n\t\treturn\n\t}\n\tp := partition(arr, L, R)\n\tqs(arr, L, p-1)\n\tqs(arr, p+1, R)\n}\n\nfunc partition(arr []int, L, R int) int {\n\tpivot := arr[R]\n\ti := L - 1\n\tfor j := L; j < R; j++ {\n\t\tif arr[j] <= pivot {\n\t\t\ti++\n\t\t\tarr[i], arr[j] = arr[j], arr[i]\n\t\t}\n\t}\n\tp := i + 1\n\tarr[p], arr[R] = arr[R], arr[p]\n\treturn p\n}\n",
    "sourceHash": "57abf2ff3013c159d3b8bfd622c07163e631a9fe179871bd254f628f8b20354c",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "baseCase",
        "range": {
          "startLine": 11,
          "endLine": 12
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 14,
          "endLine": 16
        }
      },
      {
        "id": "partition",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "loopSwap",
        "range": {
          "startLine": 24,
          "endLine": 25
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 24,
          "endLine": 25
        }
      },
      {
        "id": "pivotPlace",
        "range": {
          "startLine": 28,
          "endLine": 29
        }
      }
    ]
  }
]

export default docs
