// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/editDistance/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "editDistance.py",
    "language": "python",
    "title": "编辑距离 (Python)",
    "sourceFile": "src/codeCatalog/editDistance/langs/edit_distance.py",
    "source": "def edit_distance(a: str, b: str) -> int:\n    \"\"\"Edit distance (Levenshtein) — complete Python reference.\"\"\"\n    m = len(a)\n    n = len(b)\n    dp = [[0] * (n + 1) for _ in range(m + 1)]\n    for i in range(m + 1):\n        dp[i][0] = i\n    for j in range(n + 1):\n        dp[0][j] = j\n    for i in range(1, m + 1):\n        for j in range(1, n + 1):\n            if a[i - 1] == b[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1]\n            else:\n                dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])\n    return dp[m][n]\n",
    "sourceHash": "7a1b69649e0502928c3188515d1c4d02679287104ba04532d67717824ae12e1c",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 7
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "replace",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      }
    ]
  },
  {
    "documentId": "editDistance.cpp",
    "language": "cpp",
    "title": "编辑距离 (C++)",
    "sourceFile": "src/codeCatalog/editDistance/langs/edit_distance.cpp",
    "source": "// Edit distance (Levenshtein) — complete C++17 reference.\n#include <algorithm>\n#include <string>\n#include <vector>\n\nint editDistance(const std::string& a, const std::string& b) {\n    int m = static_cast<int>(a.size());\n    int n = static_cast<int>(b.size());\n    std::vector<std::vector<int>> dp(m + 1, std::vector<int>(n + 1, 0));\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (a[i - 1] == b[j - 1]) dp[i][j] = dp[i - 1][j - 1];\n            else {\n                dp[i][j] = 1 + std::min({dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]});\n            }\n        }\n    }\n    return dp[m][n];\n}\n",
    "sourceHash": "3524c44d568ea007c34a9917ed7fa32f7edbab6c4b4228250cca0b4b9990c718",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "replace",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "editDistance.java",
    "language": "java",
    "title": "编辑距离 (Java)",
    "sourceFile": "src/codeCatalog/editDistance/langs/EditDistance.java",
    "source": "/** Edit distance (Levenshtein) — complete Java reference. */\npublic final class EditDistance {\n    public static int editDistance(String a, String b) {\n        int m = a.length();\n        int n = b.length();\n        int[][] dp = new int[m + 1][n + 1];\n        for (int i = 0; i <= m; i++) dp[i][0] = i;\n        for (int j = 0; j <= n; j++) dp[0][j] = j;\n        for (int i = 1; i <= m; i++) {\n            for (int j = 1; j <= n; j++) {\n                if (a.charAt(i - 1) == b.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1];\n                else {\n                    dp[i][j] = 1 + Math.min(dp[i - 1][j], Math.min(dp[i][j - 1], dp[i - 1][j - 1]));\n                }\n            }\n        }\n        return dp[m][n];\n    }\n}\n",
    "sourceHash": "ec5da2fd3c40b50cce406f394c314ecb5bead7c44b26c77c369bcec91942ad26",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "replace",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      }
    ]
  },
  {
    "documentId": "editDistance.rs",
    "language": "rust",
    "title": "编辑距离 (Rust)",
    "sourceFile": "src/codeCatalog/editDistance/langs/edit_distance.rs",
    "source": "/// Edit distance (Levenshtein) — complete Rust reference.\npub fn edit_distance(a: &str, b: &str) -> usize {\n    let (a, b): (Vec<char>, Vec<char>) = (a.chars().collect(), b.chars().collect());\n    let m = a.len();\n    let n = b.len();\n    let mut dp = vec![vec![0usize; n + 1]; m + 1];\n    for i in 0..=m { dp[i][0] = i; }\n    for j in 0..=n { dp[0][j] = j; }\n    for i in 1..=m {\n        for j in 1..=n {\n            if a[i - 1] == b[j - 1] {\n                dp[i][j] = dp[i - 1][j - 1];\n            } else {\n                dp[i][j] = 1 + dp[i - 1][j].min(dp[i][j - 1]).min(dp[i - 1][j - 1]);\n            }\n        }\n    }\n    dp[m][n]\n}\n",
    "sourceHash": "c5f41b9e8a21ee1e8f77bc3a9bd34fdfdd12db13d0fc86623dba513a5fe869c5",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 11,
          "endLine": 12
        }
      },
      {
        "id": "replace",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      }
    ]
  },
  {
    "documentId": "editDistance.go",
    "language": "go",
    "title": "编辑距离 (Go)",
    "sourceFile": "src/codeCatalog/editDistance/langs/edit_distance.go",
    "source": "package algorithms\n\n// editDistance — Levenshtein distance, complete Go reference.\nfunc editDistance(a, b string) int {\n\tra, rb := []rune(a), []rune(b)\n\tm := len(ra)\n\tn := len(rb)\n\tdp := make([][]int, m+1)\n\tfor i := range dp {\n\t\tdp[i] = make([]int, n+1)\n\t}\n\tfor i := 0; i <= m; i++ {\n\t\tdp[i][0] = i\n\t}\n\tfor j := 0; j <= n; j++ {\n\t\tdp[0][j] = j\n\t}\n\tfor i := 1; i <= m; i++ {\n\t\tfor j := 1; j <= n; j++ {\n\t\t\tif ra[i-1] == rb[j-1] {\n\t\t\t\tdp[i][j] = dp[i-1][j-1]\n\t\t\t} else {\n\t\t\t\tdp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])\n\t\t\t}\n\t\t}\n\t}\n\treturn dp[m][n]\n}\n",
    "sourceHash": "2e7acc4d36f5fdf0ab0c721464863e18deac4447873614747af0849a54d0234c",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 12,
          "endLine": 14
        }
      },
      {
        "id": "equal",
        "range": {
          "startLine": 20,
          "endLine": 21
        }
      },
      {
        "id": "replace",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      }
    ]
  }
]

export default docs
