// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/prim/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "prim.py",
    "language": "python",
    "title": "Prim MST (Python)",
    "sourceFile": "src/codeCatalog/prim/langs/prim.py",
    "source": "def prim(n: int, adj: list[list[tuple[int, float]]], start: int = 0) -> tuple[float, list[int]]:\n    \"\"\"Prim MST (dense O(V^2)) — complete Python reference. adj[u] = [(v, w), ...] (undirected).\"\"\"\n    INF = float(\"inf\")\n    key = [INF] * n\n    parent = [-1] * n\n    in_mst = [False] * n\n    key[start] = 0\n    for _ in range(n):\n        u = -1\n        best = INF\n        for i in range(n):\n            if not in_mst[i] and key[i] < best:\n                best = key[i]\n                u = i\n        if u < 0:\n            break\n        in_mst[u] = True\n        for v, w in adj[u]:\n            if not in_mst[v] and w < key[v]:\n                key[v] = w\n                parent[v] = u\n    total = 0\n    for i in range(n):\n        if parent[i] >= 0:\n            total += key[i]\n    return total, parent\n",
    "sourceHash": "0c4b87ec329aadb6e1df2377752fc007818e4f7009c45ef6da4fdcf85a2d223f",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "add",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 20,
          "endLine": 21
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  },
  {
    "documentId": "prim.cpp",
    "language": "cpp",
    "title": "Prim MST (C++)",
    "sourceFile": "src/codeCatalog/prim/langs/prim.cpp",
    "source": "// Prim MST (dense O(V^2)) — complete C++17 reference. adj[u] = {(v, w), ...} (undirected).\n#include <limits>\n#include <utility>\n#include <vector>\n\nstd::pair<double, std::vector<int>> prim(int n, const std::vector<std::vector<std::pair<int, double>>>& adj, int start = 0) {\n    const double INF = std::numeric_limits<double>::infinity();\n    std::vector<double> key(n, INF);\n    std::vector<int> parent(n, -1);\n    std::vector<bool> inMst(n, false);\n    key[start] = 0;\n    for (int iter = 0; iter < n; iter++) {\n        int u = -1;\n        double best = INF;\n        for (int i = 0; i < n; i++) {\n            if (!inMst[i] && key[i] < best) {\n                best = key[i];\n                u = i;\n            }\n        }\n        if (u < 0) break;\n        inMst[u] = true;\n        for (auto [v, w] : adj[u]) {\n            if (!inMst[v] && w < key[v]) {\n                key[v] = w;\n                parent[v] = u;\n            }\n        }\n    }\n    double total = 0;\n    for (int i = 0; i < n; i++) if (parent[i] >= 0) total += key[i];\n    return {total, parent};\n}\n",
    "sourceHash": "871fc3ef58f3c4643521e9ef3f455af2f17be0f7c00ca445f0fbe37abc3c001b",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "add",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      }
    ]
  },
  {
    "documentId": "prim.java",
    "language": "java",
    "title": "Prim MST (Java)",
    "sourceFile": "src/codeCatalog/prim/langs/Prim.java",
    "source": "import java.util.Arrays;\nimport java.util.List;\n\n/** Prim MST (dense O(V^2)) — complete Java reference. adj.get(u) = arcs of u (undirected). */\npublic final class Prim {\n    public record Arc(int v, double w) {}\n    public record Result(double total, int[] parent) {}\n\n    public static Result prim(int n, List<List<Arc>> adj, int start) {\n        final double INF = Double.POSITIVE_INFINITY;\n        double[] key = new double[n];\n        Arrays.fill(key, INF);\n        int[] parent = new int[n];\n        Arrays.fill(parent, -1);\n        boolean[] inMst = new boolean[n];\n        key[start] = 0;\n        for (int iter = 0; iter < n; iter++) {\n            int u = -1;\n            double best = INF;\n            for (int i = 0; i < n; i++) {\n                if (!inMst[i] && key[i] < best) {\n                    best = key[i];\n                    u = i;\n                }\n            }\n            if (u < 0) break;\n            inMst[u] = true;\n            for (Arc a : adj.get(u)) {\n                if (!inMst[a.v()] && a.w() < key[a.v()]) {\n                    key[a.v()] = a.w();\n                    parent[a.v()] = u;\n                }\n            }\n        }\n        double total = 0;\n        for (int i = 0; i < n; i++) if (parent[i] >= 0) total += key[i];\n        return new Result(total, parent);\n    }\n}\n",
    "sourceHash": "be38f3e76d7bdd40f107f1a190b274cf29571a6b774dafdd008c325541371d5c",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "add",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 30,
          "endLine": 31
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      }
    ]
  },
  {
    "documentId": "prim.rs",
    "language": "rust",
    "title": "Prim MST (Rust)",
    "sourceFile": "src/codeCatalog/prim/langs/prim.rs",
    "source": "/// Prim MST (dense O(V^2)) — complete Rust reference. adj[u] = [(v, w), ...] (undirected).\npub fn prim(n: usize, adj: &[Vec<(usize, f64)>], start: usize) -> (f64, Vec<i64>) {\n    const INF: f64 = f64::INFINITY;\n    let mut key = vec![INF; n];\n    let mut parent = vec![-1i64; n];\n    let mut in_mst = vec![false; n];\n    key[start] = 0.0;\n    for _ in 0..n {\n        let mut u: Option<usize> = None;\n        let mut best = INF;\n        for i in 0..n {\n            if !in_mst[i] && key[i] < best {\n                best = key[i];\n                u = Some(i);\n            }\n        }\n        let Some(u) = u else { break };\n        in_mst[u] = true;\n        for &(v, w) in &adj[u] {\n            if !in_mst[v] && w < key[v] {\n                key[v] = w;\n                parent[v] = u as i64;\n            }\n        }\n    }\n    let mut total = 0.0;\n    for i in 0..n {\n        if parent[i] >= 0 {\n            total += key[i];\n        }\n    }\n    (total, parent)\n}\n",
    "sourceHash": "8ad00d112922421b0273e818000c5d7b1ae49977dd593f7ac310d47ce3cfc16b",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "add",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 21,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      }
    ]
  },
  {
    "documentId": "prim.go",
    "language": "go",
    "title": "Prim MST (Go)",
    "sourceFile": "src/codeCatalog/prim/langs/prim.go",
    "source": "package algorithms\n\nimport \"math\"\n\n// Arc is an edge u–V with weight W (undirected: listed under both endpoints).\ntype Arc struct {\n\tV int\n\tW float64\n}\n\n// prim — Prim MST (dense O(V^2)), complete Go reference.\nfunc prim(n int, adj [][]Arc, start int) (float64, []int) {\n\tINF := math.Inf(1)\n\tkey := make([]float64, n)\n\tparent := make([]int, n)\n\tinMst := make([]bool, n)\n\tfor i := range key {\n\t\tkey[i], parent[i] = INF, -1\n\t}\n\tkey[start] = 0\n\tfor iter := 0; iter < n; iter++ {\n\t\tu := -1\n\t\tbest := INF\n\t\tfor i := 0; i < n; i++ {\n\t\t\tif !inMst[i] && key[i] < best {\n\t\t\t\tbest = key[i]\n\t\t\t\tu = i\n\t\t\t}\n\t\t}\n\t\tif u < 0 {\n\t\t\tbreak\n\t\t}\n\t\tinMst[u] = true\n\t\tfor _, e := range adj[u] {\n\t\t\tif !inMst[e.V] && e.W < key[e.V] {\n\t\t\t\tkey[e.V] = e.W\n\t\t\t\tparent[e.V] = u\n\t\t\t}\n\t\t}\n\t}\n\ttotal := 0.0\n\tfor i := 0; i < n; i++ {\n\t\tif parent[i] >= 0 {\n\t\t\ttotal += key[i]\n\t\t}\n\t}\n\treturn total, parent\n}\n",
    "sourceHash": "e6f47305e1719c84bd16a4007ca2ca2219b9fc6ec54a6452d921b4d8e0e53996",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "add",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 36,
          "endLine": 37
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 47,
          "endLine": 47
        }
      }
    ]
  }
]

export default docs
