// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/kadane/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "kadane.py",
    "language": "python",
    "title": "Kadane 最大子数组 (Python)",
    "sourceFile": "src/codeCatalog/kadane/langs/kadane.py",
    "source": "def kadane(a: list[int]) -> tuple[int, int, int] | None:\n    \"\"\"Kadane max subarray (non-empty) — complete Python reference. Returns (best, start, end).\"\"\"\n    if not a:\n        return None  # empty input: there is no non-empty subarray (not a zero-sum one)\n    best = a[0]\n    cur = a[0]\n    best_start = 0\n    best_end = 0\n    cur_start = 0\n    for i in range(1, len(a)):\n        if cur + a[i] < a[i]:\n            cur = a[i]\n            cur_start = i\n        else:\n            cur = cur + a[i]\n        if cur > best:\n            best = cur\n            best_start = cur_start\n            best_end = i\n    return best, best_start, best_end\n",
    "sourceHash": "1bdce7e5c436368db2c7952447467527b109fdb1ba1a69aebd65797b957e6b96",
    "anchors": [
      {
        "id": "emptyInput",
        "range": {
          "startLine": 3,
          "endLine": 4
        }
      },
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 9
        }
      },
      {
        "id": "loopVisit",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "chooseCond",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "resetWrite",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "extendWrite",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "bestCond",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "updateBest",
        "range": {
          "startLine": 17,
          "endLine": 19
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "kadane.cpp",
    "language": "cpp",
    "title": "Kadane 最大子数组 (C++)",
    "sourceFile": "src/codeCatalog/kadane/langs/kadane.cpp",
    "source": "// Kadane max subarray (non-empty) — complete C++17 reference.\n#include <optional>\n#include <vector>\n\nstruct KadaneResult { long long best; int start; int end; };\n\nstd::optional<KadaneResult> kadane(const std::vector<long long>& a) {\n    if (a.empty()) return std::nullopt;\n    long long best = a[0];\n    long long cur = a[0];\n    int bestStart = 0;\n    int bestEnd = 0;\n    int curStart = 0;\n    for (int i = 1; i < static_cast<int>(a.size()); i++) {\n        if (cur + a[i] < a[i]) {\n            cur = a[i];\n            curStart = i;\n        } else {\n            cur = cur + a[i];\n        }\n        if (cur > best) {\n            best = cur;\n            bestStart = curStart;\n            bestEnd = i;\n        }\n    }\n    return KadaneResult{best, bestStart, bestEnd};\n}\n",
    "sourceHash": "4a430588b87a47854d982b8d77e08e77fae3de3bc5ec473863452f07b2c7d8de",
    "anchors": [
      {
        "id": "emptyInput",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "init",
        "range": {
          "startLine": 9,
          "endLine": 13
        }
      },
      {
        "id": "loopVisit",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "chooseCond",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "resetWrite",
        "range": {
          "startLine": 16,
          "endLine": 17
        }
      },
      {
        "id": "extendWrite",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "bestCond",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "updateBest",
        "range": {
          "startLine": 22,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      }
    ]
  },
  {
    "documentId": "kadane.java",
    "language": "java",
    "title": "Kadane 最大子数组 (Java)",
    "sourceFile": "src/codeCatalog/kadane/langs/Kadane.java",
    "source": "/** Kadane max subarray (non-empty) — complete Java reference. Returns {best, start, end} or null. */\npublic final class Kadane {\n    public static long[] kadane(long[] a) {\n        if (a.length == 0) return null;\n        long best = a[0];\n        long cur = a[0];\n        int bestStart = 0;\n        int bestEnd = 0;\n        int curStart = 0;\n        for (int i = 1; i < a.length; i++) {\n            if (cur + a[i] < a[i]) {\n                cur = a[i];\n                curStart = i;\n            } else {\n                cur = cur + a[i];\n            }\n            if (cur > best) {\n                best = cur;\n                bestStart = curStart;\n                bestEnd = i;\n            }\n        }\n        return new long[] {best, bestStart, bestEnd};\n    }\n}\n",
    "sourceHash": "c375b5ccef8b364a36158f59694fd0f4e0344cf22288612c9807c61be70fa2f8",
    "anchors": [
      {
        "id": "emptyInput",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 9
        }
      },
      {
        "id": "loopVisit",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "chooseCond",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "resetWrite",
        "range": {
          "startLine": 12,
          "endLine": 13
        }
      },
      {
        "id": "extendWrite",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "bestCond",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "updateBest",
        "range": {
          "startLine": 18,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      }
    ]
  },
  {
    "documentId": "kadane.rs",
    "language": "rust",
    "title": "Kadane 最大子数组 (Rust)",
    "sourceFile": "src/codeCatalog/kadane/langs/kadane.rs",
    "source": "/// Kadane max subarray (non-empty) — complete Rust reference. Returns (best, start, end).\npub fn kadane(a: &[i64]) -> Option<(i64, usize, usize)> {\n    if a.is_empty() {\n        return None; // empty input: there is no non-empty subarray\n    }\n    let mut best = a[0];\n    let mut cur = a[0];\n    let mut best_start = 0;\n    let mut best_end = 0;\n    let mut cur_start = 0;\n    for i in 1..a.len() {\n        if cur + a[i] < a[i] {\n            cur = a[i];\n            cur_start = i;\n        } else {\n            cur = cur + a[i];\n        }\n        if cur > best {\n            best = cur;\n            best_start = cur_start;\n            best_end = i;\n        }\n    }\n    Some((best, best_start, best_end))\n}\n",
    "sourceHash": "263a82f35d652a843ea9701471999a8124d369d803a5111d56f0c5e855d850f2",
    "anchors": [
      {
        "id": "emptyInput",
        "range": {
          "startLine": 3,
          "endLine": 4
        }
      },
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 10
        }
      },
      {
        "id": "loopVisit",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "chooseCond",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "resetWrite",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "extendWrite",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "bestCond",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "updateBest",
        "range": {
          "startLine": 19,
          "endLine": 21
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      }
    ]
  },
  {
    "documentId": "kadane.go",
    "language": "go",
    "title": "Kadane 最大子数组 (Go)",
    "sourceFile": "src/codeCatalog/kadane/langs/kadane.go",
    "source": "package algorithms\n\n// kadaneResult is the best non-empty subarray: its sum and inclusive bounds.\ntype kadaneResult struct{ best, start, end int }\n\n// kadane max subarray (non-empty) — complete Go reference; nil for empty input.\nfunc kadane(a []int) *kadaneResult {\n\tif len(a) == 0 {\n\t\treturn nil\n\t}\n\tbest := a[0]\n\tcur := a[0]\n\tbestStart := 0\n\tbestEnd := 0\n\tcurStart := 0\n\tfor i := 1; i < len(a); i++ {\n\t\tif cur+a[i] < a[i] {\n\t\t\tcur = a[i]\n\t\t\tcurStart = i\n\t\t} else {\n\t\t\tcur = cur + a[i]\n\t\t}\n\t\tif cur > best {\n\t\t\tbest = cur\n\t\t\tbestStart = curStart\n\t\t\tbestEnd = i\n\t\t}\n\t}\n\treturn &kadaneResult{best, bestStart, bestEnd}\n}\n",
    "sourceHash": "722a3c45bf551f7d10937e9d1d96a22133d165b98543f150caad6c15fb12ee70",
    "anchors": [
      {
        "id": "emptyInput",
        "range": {
          "startLine": 8,
          "endLine": 9
        }
      },
      {
        "id": "init",
        "range": {
          "startLine": 11,
          "endLine": 15
        }
      },
      {
        "id": "loopVisit",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "chooseCond",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "resetWrite",
        "range": {
          "startLine": 18,
          "endLine": 19
        }
      },
      {
        "id": "extendWrite",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "bestCond",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "updateBest",
        "range": {
          "startLine": 24,
          "endLine": 26
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      }
    ]
  }
]

export default docs
