// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/bfs/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "bfs.py",
    "language": "python",
    "title": "BFS (Python)",
    "sourceFile": "src/codeCatalog/bfs/langs/bfs.py",
    "source": "def bfs(adj: list[list[int]], start: int) -> tuple[list[int], list[int]]:\n    \"\"\"BFS shortest path on unweighted graph — complete Python reference.\"\"\"\n    n = len(adj)\n    dist = [-1] * n\n    parent = [-1] * n\n    q = [start]\n    dist[start] = 0\n    head = 0\n    while head < len(q):\n        u = q[head]\n        head += 1\n        for v in adj[u]:\n            if dist[v] < 0:\n                dist[v] = dist[u] + 1\n                parent[v] = u\n                q.append(v)\n    return dist, parent\n",
    "sourceHash": "61c4825c37090e6e8b08b418428b103369add26a08119cd0eb3ac4eb4bab69e0",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "dequeue",
        "range": {
          "startLine": 10,
          "endLine": 11
        }
      },
      {
        "id": "visit",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "enqueue",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      }
    ]
  },
  {
    "documentId": "bfs.cpp",
    "language": "cpp",
    "title": "BFS (C++)",
    "sourceFile": "src/codeCatalog/bfs/langs/bfs.cpp",
    "source": "// BFS shortest path on unweighted graph — complete C++17 reference.\n#include <utility>\n#include <vector>\n\nstd::pair<std::vector<int>, std::vector<int>> bfs(const std::vector<std::vector<int>>& adj, int start) {\n    int n = static_cast<int>(adj.size());\n    std::vector<int> dist(n, -1);\n    std::vector<int> parent(n, -1);\n    std::vector<int> q{start};\n    dist[start] = 0;\n    size_t head = 0;\n    while (head < q.size()) {\n        int u = q[head++];\n        for (int v : adj[u]) {\n            if (dist[v] < 0) {\n                dist[v] = dist[u] + 1;\n                parent[v] = u;\n                q.push_back(v);\n            }\n        }\n    }\n    return {dist, parent};\n}\n",
    "sourceHash": "8938adbfee3e0e5671a379969dffbd9579c9a259c0708e090048fdd3ea370567",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "dequeue",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "visit",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "enqueue",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      }
    ]
  },
  {
    "documentId": "bfs.java",
    "language": "java",
    "title": "BFS (Java)",
    "sourceFile": "src/codeCatalog/bfs/langs/Bfs.java",
    "source": "import java.util.ArrayList;\nimport java.util.Arrays;\nimport java.util.List;\n\n/** BFS shortest path on unweighted graph — complete Java reference. */\npublic final class Bfs {\n    public record Result(int[] dist, int[] parent) {}\n\n    public static Result bfs(List<List<Integer>> adj, int start) {\n        int n = adj.size();\n        int[] dist = new int[n];\n        int[] parent = new int[n];\n        Arrays.fill(dist, -1);\n        Arrays.fill(parent, -1);\n        List<Integer> q = new ArrayList<>(List.of(start));\n        dist[start] = 0;\n        int head = 0;\n        while (head < q.size()) {\n            int u = q.get(head++);\n            for (int v : adj.get(u)) {\n                if (dist[v] < 0) {\n                    dist[v] = dist[u] + 1;\n                    parent[v] = u;\n                    q.add(v);\n                }\n            }\n        }\n        return new Result(dist, parent);\n    }\n}\n",
    "sourceHash": "919d0d7d44292fe847febedeb705aeff900d0f252c1e5d64f8959b275826368a",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "dequeue",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "visit",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "enqueue",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      }
    ]
  },
  {
    "documentId": "bfs.rs",
    "language": "rust",
    "title": "BFS (Rust)",
    "sourceFile": "src/codeCatalog/bfs/langs/bfs.rs",
    "source": "/// BFS shortest path on unweighted graph — complete Rust reference.\npub fn bfs(adj: &[Vec<usize>], start: usize) -> (Vec<i64>, Vec<i64>) {\n    let n = adj.len();\n    let mut dist = vec![-1i64; n];\n    let mut parent = vec![-1i64; n];\n    let mut q: Vec<usize> = vec![start];\n    dist[start] = 0;\n    let mut head = 0;\n    while head < q.len() {\n        let u = q[head];\n        head += 1;\n        for &v in &adj[u] {\n            if dist[v] < 0 {\n                dist[v] = dist[u] + 1;\n                parent[v] = u as i64;\n                q.push(v);\n            }\n        }\n    }\n    (dist, parent)\n}\n",
    "sourceHash": "a0e15a48bab1d537fc790be3c0b525bf8dc0504c78e848c2fa5442d12161d600",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "dequeue",
        "range": {
          "startLine": 10,
          "endLine": 11
        }
      },
      {
        "id": "visit",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "enqueue",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "bfs.go",
    "language": "go",
    "title": "BFS (Go)",
    "sourceFile": "src/codeCatalog/bfs/langs/bfs.go",
    "source": "package algorithms\n\n// bfs — BFS shortest path on an unweighted graph, complete Go reference.\nfunc bfs(adj [][]int, start int) ([]int, []int) {\n\tn := len(adj)\n\tdist := make([]int, n)\n\tparent := make([]int, n)\n\tfor i := range dist {\n\t\tdist[i], parent[i] = -1, -1\n\t}\n\tq := []int{start}\n\tdist[start] = 0\n\thead := 0\n\tfor head < len(q) {\n\t\tu := q[head]\n\t\thead++\n\t\tfor _, v := range adj[u] {\n\t\t\tif dist[v] < 0 {\n\t\t\t\tdist[v] = dist[u] + 1\n\t\t\t\tparent[v] = u\n\t\t\t\tq = append(q, v)\n\t\t\t}\n\t\t}\n\t}\n\treturn dist, parent\n}\n",
    "sourceHash": "7682e9742d5fda199f4fb443534d8dd36ad22bf10e52505007f47dd5504e08fe",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "dequeue",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "visit",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "enqueue",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      }
    ]
  }
]

export default docs
