// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/dijkstra/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "dijkstra.naive.py",
    "language": "python",
    "title": "朴素 Dijkstra (Python)",
    "sourceFile": "src/codeCatalog/dijkstra/langs/dijkstra_naive.py",
    "source": "def naive_dijkstra(n: int, start: int, adj: list[list[tuple[int, float]]]) -> tuple[list[float], list[int]]:\n    \"\"\"Naive Dijkstra (non-negative weights) — complete Python reference. adj[u] = [(v, w), ...].\"\"\"\n    INF = float(\"inf\")\n    dist = [INF] * n\n    done = [False] * n\n    parent = [-1] * n\n    dist[start] = 0\n    for _ in range(n):\n        u = -1\n        best = INF\n        for i in range(n):\n            if not done[i] and dist[i] < best:\n                best = dist[i]\n                u = i\n        if u < 0 or best == INF:\n            break\n        done[u] = True\n        for v, w in adj[u]:\n            if dist[u] + w < dist[v]:\n                dist[v] = dist[u] + w\n                parent[v] = u\n    return dist, parent\n",
    "sourceHash": "397b68463338b6b8c7b5018ceecc1285e27b60e3206f8af8d5ca4c86b77bd68a",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "relax.condition",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "relax.update",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      }
    ]
  },
  {
    "documentId": "dijkstra.naive.cpp",
    "language": "cpp",
    "title": "朴素 Dijkstra (C++)",
    "sourceFile": "src/codeCatalog/dijkstra/langs/dijkstra_naive.cpp",
    "source": "// Naive Dijkstra (non-negative weights) — complete C++17 reference. adj[u] = {(v, w), ...}.\n#include <limits>\n#include <utility>\n#include <vector>\n\nstd::pair<std::vector<double>, std::vector<int>> naiveDijkstra(int n, int start, const std::vector<std::vector<std::pair<int, double>>>& adj) {\n    const double INF = std::numeric_limits<double>::infinity();\n    std::vector<double> dist(n, INF);\n    std::vector<bool> done(n, false);\n    std::vector<int> parent(n, -1);\n    dist[start] = 0;\n    for (int iter = 0; iter < n; iter++) {\n        int u = -1;\n        double best = INF;\n        for (int i = 0; i < n; i++) {\n            if (!done[i] && dist[i] < best) {\n                best = dist[i];\n                u = i;\n            }\n        }\n        if (u < 0 || best == INF) break;\n        done[u] = true;\n        for (auto [v, w] : adj[u]) {\n            if (dist[u] + w < dist[v]) {\n                dist[v] = dist[u] + w;\n                parent[v] = u;\n            }\n        }\n    }\n    return {dist, parent};\n}\n",
    "sourceHash": "bf8b484a4c88568662d1f60a64c8bcb8597add00ac153cc6b4d75cb5b07ac1c8",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "relax.condition",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "relax.update",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      }
    ]
  },
  {
    "documentId": "dijkstra.naive.java",
    "language": "java",
    "title": "朴素 Dijkstra (Java)",
    "sourceFile": "src/codeCatalog/dijkstra/langs/NaiveDijkstra.java",
    "source": "import java.util.Arrays;\nimport java.util.List;\n\n/** Naive Dijkstra (non-negative weights) — complete Java reference. */\npublic final class NaiveDijkstra {\n    public record Arc(int v, double w) {}\n    public record Result(double[] dist, int[] parent) {}\n\n    public static Result naiveDijkstra(int n, int start, List<List<Arc>> adj) {\n        final double INF = Double.POSITIVE_INFINITY;\n        double[] dist = new double[n];\n        Arrays.fill(dist, INF);\n        boolean[] done = new boolean[n];\n        int[] parent = new int[n];\n        Arrays.fill(parent, -1);\n        dist[start] = 0;\n        for (int iter = 0; iter < n; iter++) {\n            int u = -1;\n            double best = INF;\n            for (int i = 0; i < n; i++) {\n                if (!done[i] && dist[i] < best) {\n                    best = dist[i];\n                    u = i;\n                }\n            }\n            if (u < 0 || best == INF) break;\n            done[u] = true;\n            for (Arc a : adj.get(u)) {\n                if (dist[u] + a.w() < dist[a.v()]) {\n                    dist[a.v()] = dist[u] + a.w();\n                    parent[a.v()] = u;\n                }\n            }\n        }\n        return new Result(dist, parent);\n    }\n}\n",
    "sourceHash": "ce5be19f2e38947fc21b880ec874b49050446043f04a27bb95b45999c84ce72f",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "relax.condition",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "relax.update",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      }
    ]
  },
  {
    "documentId": "dijkstra.naive.rs",
    "language": "rust",
    "title": "朴素 Dijkstra (Rust)",
    "sourceFile": "src/codeCatalog/dijkstra/langs/dijkstra_naive.rs",
    "source": "/// Naive Dijkstra (non-negative weights) — complete Rust reference. adj[u] = [(v, w), ...].\npub fn naive_dijkstra(n: usize, start: usize, adj: &[Vec<(usize, f64)>]) -> (Vec<f64>, Vec<i64>) {\n    const INF: f64 = f64::INFINITY;\n    let mut dist = vec![INF; n];\n    let mut done = vec![false; n];\n    let mut parent = vec![-1i64; n];\n    dist[start] = 0.0;\n    for _ in 0..n {\n        let mut u: Option<usize> = None;\n        let mut best = INF;\n        for i in 0..n {\n            if !done[i] && dist[i] < best {\n                best = dist[i];\n                u = Some(i);\n            }\n        }\n        let u = match u { Some(u) if best != INF => u, _ => break };\n        done[u] = true;\n        for &(v, w) in &adj[u] {\n            if dist[u] + w < dist[v] {\n                dist[v] = dist[u] + w;\n                parent[v] = u as i64;\n            }\n        }\n    }\n    (dist, parent)\n}\n",
    "sourceHash": "e815a6dd02514c3de08f893dc19bc15b01a0e72183dc010db98123cceaa46724",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "relax.condition",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "relax.update",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  },
  {
    "documentId": "dijkstra.naive.go",
    "language": "go",
    "title": "朴素 Dijkstra (Go)",
    "sourceFile": "src/codeCatalog/dijkstra/langs/dijkstra_naive.go",
    "source": "package algorithms\n\nimport \"math\"\n\n// Arc is an outgoing edge u→V with weight W (adj[u] lists the arcs of u).\ntype Arc struct {\n\tV int\n\tW float64\n}\n\n// naiveDijkstra — naive Dijkstra (non-negative weights), complete Go reference.\nfunc naiveDijkstra(n, start int, adj [][]Arc) ([]float64, []int) {\n\tINF := math.Inf(1)\n\tdist := make([]float64, n)\n\tdone := make([]bool, n)\n\tparent := make([]int, n)\n\tfor i := range dist {\n\t\tdist[i], parent[i] = INF, -1\n\t}\n\tdist[start] = 0\n\tfor iter := 0; iter < n; iter++ {\n\t\tu := -1\n\t\tbest := INF\n\t\tfor i := 0; i < n; i++ {\n\t\t\tif !done[i] && dist[i] < best {\n\t\t\t\tbest = dist[i]\n\t\t\t\tu = i\n\t\t\t}\n\t\t}\n\t\tif u < 0 || best == INF {\n\t\t\tbreak\n\t\t}\n\t\tdone[u] = true\n\t\tfor _, e := range adj[u] {\n\t\t\tif dist[u]+e.W < dist[e.V] {\n\t\t\t\tdist[e.V] = dist[u] + e.W\n\t\t\t\tparent[e.V] = u\n\t\t\t}\n\t\t}\n\t}\n\treturn dist, parent\n}\n",
    "sourceHash": "e64a450132a12f5f0751b9192685fb4f232ff70fb156f31b346b07d561b70331",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "selectMin",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "relax.condition",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "relax.update",
        "range": {
          "startLine": 36,
          "endLine": 36
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 41,
          "endLine": 41
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 41,
          "endLine": 41
        }
      }
    ]
  }
]

export default docs
