// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/dp1dCorrect/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.dp1dCorrect.py",
    "language": "python",
    "title": "0-1 背包一维正确 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dCorrect/langs/knapsack_dp1d_correct.py",
    "source": "def knapsack_dp1d_correct(weights: list[int], values: list[int], W: int) -> int:\n    \"\"\"0-1 knapsack 1D correct (reverse) — complete Python reference.\"\"\"\n    dp = [0] * (W + 1)\n    for i in range(len(weights)):\n        wt = weights[i]\n        val = values[i]\n        for w in range(W, wt - 1, -1):\n            dp[w] = max(dp[w], dp[w - wt] + val)\n    return dp[W]\n",
    "sourceHash": "b45c3d384ccb4148025121c4ccf5d7bb963ad3b47f5526f310eecfe51fd86b31",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "reverse",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dCorrect.cpp",
    "language": "cpp",
    "title": "0-1 背包一维正确 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dCorrect/langs/knapsack_dp1d_correct.cpp",
    "source": "// 0-1 knapsack 1D correct (reverse) — complete C++17 reference.\n#include <algorithm>\n#include <vector>\n\nlong long knapsackDp1dCorrect(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    std::vector<long long> dp(W + 1, 0);\n    for (size_t i = 0; i < weights.size(); i++) {\n        int wt = weights[i];\n        long long val = values[i];\n        for (int w = W; w >= wt; w--) {\n            dp[w] = std::max(dp[w], dp[w - wt] + val);\n        }\n    }\n    return dp[W];\n}\n",
    "sourceHash": "a3b5f8377f173adfac6e33724080951e8e323a31079af15e08cd2e439c6f4e37",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "reverse",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dCorrect.java",
    "language": "java",
    "title": "0-1 背包一维正确 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dCorrect/langs/KnapsackDp1dCorrect.java",
    "source": "/** 0-1 knapsack 1D correct (reverse) — complete Java reference. */\npublic final class KnapsackDp1dCorrect {\n    public static long knapsackDp1dCorrect(int[] weights, long[] values, int W) {\n        long[] dp = new long[W + 1];\n        for (int i = 0; i < weights.length; i++) {\n            int wt = weights[i];\n            long val = values[i];\n            for (int w = W; w >= wt; w--) {\n                dp[w] = Math.max(dp[w], dp[w - wt] + val);\n            }\n        }\n        return dp[W];\n    }\n}\n",
    "sourceHash": "97bf123117c88fabe57b2c3d69ac514607e7dcc68f1a90016badaafe68e1263c",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "reverse",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dCorrect.rs",
    "language": "rust",
    "title": "0-1 背包一维正确 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dCorrect/langs/knapsack_dp1d_correct.rs",
    "source": "/// 0-1 knapsack 1D correct (reverse) — complete Rust reference (capacity W is `cap`).\npub fn knapsack_dp1d_correct(weights: &[usize], values: &[i64], cap: usize) -> i64 {\n    let mut dp = vec![0i64; cap + 1];\n    for i in 0..weights.len() {\n        let wt = weights[i];\n        let val = values[i];\n        for w in (wt..=cap).rev() {\n            dp[w] = dp[w].max(dp[w - wt] + val);\n        }\n    }\n    dp[cap]\n}\n",
    "sourceHash": "095b6de787d2ad70b6834e358c3c0bb3daa6aa99e6816f685ee715266c553d10",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "reverse",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      }
    ]
  },
  {
    "documentId": "knapsack.dp1dCorrect.go",
    "language": "go",
    "title": "0-1 背包一维正确 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/dp1dCorrect/langs/knapsack_dp1d_correct.go",
    "source": "package algorithms\n\n// knapsackDp1dCorrect — 0-1 knapsack 1D correct (reverse), complete Go reference.\nfunc knapsackDp1dCorrect(weights, values []int, W int) int {\n\tdp := make([]int, W+1)\n\tfor i := 0; i < len(weights); i++ {\n\t\twt := weights[i]\n\t\tval := values[i]\n\t\tfor w := W; w >= wt; w-- {\n\t\t\tdp[w] = max(dp[w], dp[w-wt]+val)\n\t\t}\n\t}\n\treturn dp[W]\n}\n",
    "sourceHash": "d36dcfa88c7c2f26ff47bf689d5708521bb9063eaf38cdcfc0309b96d205e807",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "reverse",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      }
    ]
  }
]

export default docs
