// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/bellmanFord/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "bellmanFord.py",
    "language": "python",
    "title": "Bellman-Ford (Python)",
    "sourceFile": "src/codeCatalog/bellmanFord/langs/bellman_ford.py",
    "source": "from typing import NamedTuple\n\n\nclass Edge(NamedTuple):\n    u: int\n    v: int\n    w: float\n\n\ndef bellman_ford(n: int, edges: list[Edge], start: int) -> tuple[list[float], list[int], bool]:\n    \"\"\"Bellman-Ford — complete Python reference. Returns (dist, parent, neg_cycle).\"\"\"\n    INF = float(\"inf\")\n    dist = [INF] * n\n    parent = [-1] * n\n    dist[start] = 0\n    for _ in range(n - 1):\n        for e in edges:\n            if dist[e.u] + e.w < dist[e.v]:\n                dist[e.v] = dist[e.u] + e.w\n                parent[e.v] = e.u\n    neg_cycle = False\n    for e in edges:\n        if dist[e.u] + e.w < dist[e.v]:\n            neg_cycle = True\n            break\n    return dist, parent, neg_cycle\n",
    "sourceHash": "0430a51fbb8b59327ddaf7269f02e49bb7d69c16b78f7fc8937431ddf6e8ac9b",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "round",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "negCycle",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  },
  {
    "documentId": "bellmanFord.cpp",
    "language": "cpp",
    "title": "Bellman-Ford (C++)",
    "sourceFile": "src/codeCatalog/bellmanFord/langs/bellman_ford.cpp",
    "source": "// Bellman-Ford — complete C++17 reference.\n#include <limits>\n#include <tuple>\n#include <vector>\n\nstruct Edge { int u, v; double w; };\n\nstd::tuple<std::vector<double>, std::vector<int>, bool> bellmanFord(int n, const std::vector<Edge>& edges, int start) {\n    const double INF = std::numeric_limits<double>::infinity();\n    std::vector<double> dist(n, INF);\n    std::vector<int> parent(n, -1);\n    dist[start] = 0;\n    for (int i = 0; i < n - 1; i++) {\n        for (const Edge& e : edges) {\n            if (dist[e.u] + e.w < dist[e.v]) {\n                dist[e.v] = dist[e.u] + e.w;\n                parent[e.v] = e.u;\n            }\n        }\n    }\n    bool negCycle = false;\n    for (const Edge& e : edges) {\n        if (dist[e.u] + e.w < dist[e.v]) {\n            negCycle = true;\n            break;\n        }\n    }\n    return {dist, parent, negCycle};\n}\n",
    "sourceHash": "facc2da3296be353faceb17572d368ecc948356940a9c765ee8814ec869defc4",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "round",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "negCycle",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      }
    ]
  },
  {
    "documentId": "bellmanFord.java",
    "language": "java",
    "title": "Bellman-Ford (Java)",
    "sourceFile": "src/codeCatalog/bellmanFord/langs/BellmanFord.java",
    "source": "import java.util.Arrays;\nimport java.util.List;\n\n/** Bellman-Ford — complete Java reference. */\npublic final class BellmanFord {\n    public record Edge(int u, int v, double w) {}\n    public record Result(double[] dist, int[] parent, boolean negCycle) {}\n\n    public static Result bellmanFord(int n, List<Edge> edges, int start) {\n        final double INF = Double.POSITIVE_INFINITY;\n        double[] dist = new double[n];\n        Arrays.fill(dist, INF);\n        int[] parent = new int[n];\n        Arrays.fill(parent, -1);\n        dist[start] = 0;\n        for (int i = 0; i < n - 1; i++) {\n            for (Edge e : edges) {\n                if (dist[e.u()] + e.w() < dist[e.v()]) {\n                    dist[e.v()] = dist[e.u()] + e.w();\n                    parent[e.v()] = e.u();\n                }\n            }\n        }\n        boolean negCycle = false;\n        for (Edge e : edges) {\n            if (dist[e.u()] + e.w() < dist[e.v()]) {\n                negCycle = true;\n                break;\n            }\n        }\n        return new Result(dist, parent, negCycle);\n    }\n}\n",
    "sourceHash": "f20359862706ee557e248100255773912c722709081acdbf66a3a4c18b49d3e6",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "round",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "negCycle",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      }
    ]
  },
  {
    "documentId": "bellmanFord.rs",
    "language": "rust",
    "title": "Bellman-Ford (Rust)",
    "sourceFile": "src/codeCatalog/bellmanFord/langs/bellman_ford.rs",
    "source": "/// Bellman-Ford — complete Rust reference. Returns (dist, parent, neg_cycle).\npub struct Edge {\n    pub u: usize,\n    pub v: usize,\n    pub w: f64,\n}\n\npub fn bellman_ford(n: usize, edges: &[Edge], start: usize) -> (Vec<f64>, Vec<i64>, bool) {\n    const INF: f64 = f64::INFINITY;\n    let mut dist = vec![INF; n];\n    let mut parent = vec![-1i64; n];\n    dist[start] = 0.0;\n    for _ in 0..n.saturating_sub(1) {\n        for e in edges {\n            if dist[e.u] + e.w < dist[e.v] {\n                dist[e.v] = dist[e.u] + e.w;\n                parent[e.v] = e.u as i64;\n            }\n        }\n    }\n    let mut neg_cycle = false;\n    for e in edges {\n        if dist[e.u] + e.w < dist[e.v] {\n            neg_cycle = true;\n            break;\n        }\n    }\n    (dist, parent, neg_cycle)\n}\n",
    "sourceHash": "adab10a7ab60badd431917dcf0815ee650f6b17dad272fdfd197f4c412ddfb04",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "round",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "negCycle",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      }
    ]
  },
  {
    "documentId": "bellmanFord.go",
    "language": "go",
    "title": "Bellman-Ford (Go)",
    "sourceFile": "src/codeCatalog/bellmanFord/langs/bellman_ford.go",
    "source": "package algorithms\n\nimport \"math\"\n\n// Edge is a directed weighted edge U→V.\ntype Edge struct {\n\tU, V int\n\tW    float64\n}\n\n// bellmanFord — Bellman-Ford, complete Go reference. Returns (dist, parent, negCycle).\nfunc bellmanFord(n int, edges []Edge, start int) ([]float64, []int, bool) {\n\tINF := math.Inf(1)\n\tdist := make([]float64, n)\n\tparent := make([]int, n)\n\tfor i := range dist {\n\t\tdist[i], parent[i] = INF, -1\n\t}\n\tdist[start] = 0\n\tfor i := 0; i < n-1; i++ {\n\t\tfor _, e := range edges {\n\t\t\tif dist[e.U]+e.W < dist[e.V] {\n\t\t\t\tdist[e.V] = dist[e.U] + e.W\n\t\t\t\tparent[e.V] = e.U\n\t\t\t}\n\t\t}\n\t}\n\tnegCycle := false\n\tfor _, e := range edges {\n\t\tif dist[e.U]+e.W < dist[e.V] {\n\t\t\tnegCycle = true\n\t\t\tbreak\n\t\t}\n\t}\n\treturn dist, parent, negCycle\n}\n",
    "sourceHash": "be5d6713cd35ffb61b9eb0bb264e6f2948aa2d74a397d5693441b62c3cf1c719",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "round",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "relax",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "update",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "negCycle",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      }
    ]
  }
]

export default docs
