// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/brute/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.brute.py",
    "language": "python",
    "title": "0-1 背包暴力枚举 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/brute/langs/knapsack_brute.py",
    "source": "def knapsack_brute(weights: list[int], values: list[int], W: int) -> int:\n    \"\"\"0-1 knapsack brute force — complete Python reference.\"\"\"\n    n = len(weights)\n    best = 0\n    total = 1 << n\n    for mask in range(total):\n        wt = 0\n        val = 0\n        for i in range(n):\n            if mask & (1 << i):\n                wt += weights[i]\n                val += values[i]\n        if wt <= W and val > best:\n            best = val\n    return best\n",
    "sourceHash": "a96641fb269ce3f4cbb0bf6704edccd64a8735aa4008a2a375fcbfb0ecd62362",
    "anchors": [
      {
        "id": "enum",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "sum",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "feasible",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  },
  {
    "documentId": "knapsack.brute.cpp",
    "language": "cpp",
    "title": "0-1 背包暴力枚举 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/brute/langs/knapsack_brute.cpp",
    "source": "// 0-1 knapsack brute force — complete C++17 reference.\n#include <vector>\n\nlong long knapsackBrute(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    int n = static_cast<int>(weights.size());\n    long long best = 0;\n    long long total = 1LL << n;\n    for (long long mask = 0; mask < total; mask++) {\n        long long wt = 0;\n        long long val = 0;\n        for (int i = 0; i < n; i++) {\n            if (mask & (1LL << i)) {\n                wt += weights[i];\n                val += values[i];\n            }\n        }\n        if (wt <= W && val > best) best = val;\n    }\n    return best;\n}\n",
    "sourceHash": "ee7a61e58f4dcb0fd78d17f36d5394171c213df8b1140f7961382764dccc4b4a",
    "anchors": [
      {
        "id": "enum",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "sum",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "feasible",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "knapsack.brute.java",
    "language": "java",
    "title": "0-1 背包暴力枚举 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/brute/langs/KnapsackBrute.java",
    "source": "/** 0-1 knapsack brute force — complete Java reference. */\npublic final class KnapsackBrute {\n    public static long knapsackBrute(int[] weights, long[] values, int W) {\n        int n = weights.length;\n        long best = 0;\n        long total = 1L << n;\n        for (long mask = 0; mask < total; mask++) {\n            long wt = 0;\n            long val = 0;\n            for (int i = 0; i < n; i++) {\n                if ((mask & (1L << i)) != 0) {\n                    wt += weights[i];\n                    val += values[i];\n                }\n            }\n            if (wt <= W && val > best) best = val;\n        }\n        return best;\n    }\n}\n",
    "sourceHash": "079d2b5124078614a9c64f671a46aa059ac5276d002c3b29e9fc2e74b864c8f1",
    "anchors": [
      {
        "id": "enum",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "sum",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "feasible",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      }
    ]
  },
  {
    "documentId": "knapsack.brute.rs",
    "language": "rust",
    "title": "0-1 背包暴力枚举 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/brute/langs/knapsack_brute.rs",
    "source": "/// 0-1 knapsack brute force — complete Rust reference (capacity W is `cap`).\npub fn knapsack_brute(weights: &[usize], values: &[i64], cap: usize) -> i64 {\n    let n = weights.len();\n    let mut best = 0;\n    let total: u64 = 1 << n;\n    for mask in 0..total {\n        let mut wt = 0;\n        let mut val = 0;\n        for i in 0..n {\n            if mask & (1 << i) != 0 {\n                wt += weights[i];\n                val += values[i];\n            }\n        }\n        if wt <= cap && val > best {\n            best = val;\n        }\n    }\n    best\n}\n",
    "sourceHash": "1b082e2463881e9e27e4a1b31f1b62672d0ca018a6cef91ffe7314a5fafcefdc",
    "anchors": [
      {
        "id": "enum",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "sum",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "feasible",
        "range": {
          "startLine": 15,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "knapsack.brute.go",
    "language": "go",
    "title": "0-1 背包暴力枚举 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/brute/langs/knapsack_brute.go",
    "source": "package algorithms\n\n// knapsackBrute — 0-1 knapsack brute force, complete Go reference.\nfunc knapsackBrute(weights, values []int, W int) int {\n\tn := len(weights)\n\tbest := 0\n\ttotal := 1 << n\n\tfor mask := 0; mask < total; mask++ {\n\t\twt := 0\n\t\tval := 0\n\t\tfor i := 0; i < n; i++ {\n\t\t\tif mask&(1<<i) != 0 {\n\t\t\t\twt += weights[i]\n\t\t\t\tval += values[i]\n\t\t\t}\n\t\t}\n\t\tif wt <= W && val > best {\n\t\t\tbest = val\n\t\t}\n\t}\n\treturn best\n}\n",
    "sourceHash": "d1021f0d55e1cbc0ee40d7b251c8e2ae94f35839e5efc9029720ca7b02e2682e",
    "anchors": [
      {
        "id": "enum",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "sum",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "feasible",
        "range": {
          "startLine": 17,
          "endLine": 18
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      }
    ]
  }
]

export default docs
