// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/insertionSort/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "insertionSort.py",
    "language": "python",
    "title": "插入排序 (Python)",
    "sourceFile": "src/codeCatalog/insertionSort/langs/insertion_sort.py",
    "source": "def insertion_sort(a: list[int]) -> list[int]:\n    \"\"\"Insertion sort — complete Python reference.\"\"\"\n    arr = list(a)\n    for i in range(1, len(arr)):\n        key = arr[i]\n        j = i - 1\n        while j >= 0 and arr[j] > key:\n            arr[j + 1] = arr[j]\n            j -= 1\n        arr[j + 1] = key\n    return arr\n",
    "sourceHash": "7eb60f7e66bf9a0558bc0dc6bb04d513c4c7f96175739b285ccab7ca1eba7564",
    "anchors": [
      {
        "id": "outer",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "shift",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "insert",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      }
    ]
  },
  {
    "documentId": "insertionSort.cpp",
    "language": "cpp",
    "title": "插入排序 (C++)",
    "sourceFile": "src/codeCatalog/insertionSort/langs/insertion_sort.cpp",
    "source": "// Insertion sort — complete C++17 reference.\n#include <vector>\n\nstd::vector<int> insertionSort(std::vector<int> arr) {\n    for (int i = 1; i < static_cast<int>(arr.size()); i++) {\n        int key = arr[i];\n        int j = i - 1;\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j--;\n        }\n        arr[j + 1] = key;\n    }\n    return arr;\n}\n",
    "sourceHash": "3d0f4b88cbe8cbc494f2d312435d616be64d0691f0f9e597ce0dca3aad804d47",
    "anchors": [
      {
        "id": "outer",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "shift",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "insert",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "insertionSort.java",
    "language": "java",
    "title": "插入排序 (Java)",
    "sourceFile": "src/codeCatalog/insertionSort/langs/InsertionSort.java",
    "source": "/** Insertion sort — complete Java reference. */\npublic final class InsertionSort {\n    public static int[] insertionSort(int[] a) {\n        int[] arr = a.clone();\n        for (int i = 1; i < arr.length; i++) {\n            int key = arr[i];\n            int j = i - 1;\n            while (j >= 0 && arr[j] > key) {\n                arr[j + 1] = arr[j];\n                j--;\n            }\n            arr[j + 1] = key;\n        }\n        return arr;\n    }\n}\n",
    "sourceHash": "94196cfc200c01e8ddf20c72cd87f1dceb55f7a47ff9c31549d6629efbf87099",
    "anchors": [
      {
        "id": "outer",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "shift",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "insert",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "insertionSort.rs",
    "language": "rust",
    "title": "插入排序 (Rust)",
    "sourceFile": "src/codeCatalog/insertionSort/langs/insertion_sort.rs",
    "source": "/// Insertion sort — complete Rust reference (j is signed so it can reach -1, like the TypeScript).\npub fn insertion_sort(a: &[i64]) -> Vec<i64> {\n    let mut arr = a.to_vec();\n    for i in 1..arr.len() {\n        let key = arr[i];\n        let mut j = i as isize - 1;\n        while j >= 0 && arr[j as usize] > key {\n            arr[(j + 1) as usize] = arr[j as usize];\n            j -= 1;\n        }\n        arr[(j + 1) as usize] = key;\n    }\n    arr\n}\n",
    "sourceHash": "b374cbf76732eff301a530e9c999b14c928ae90aca73acb5aeb1e7b2ab27a81c",
    "anchors": [
      {
        "id": "outer",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "shift",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "insert",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      }
    ]
  },
  {
    "documentId": "insertionSort.go",
    "language": "go",
    "title": "插入排序 (Go)",
    "sourceFile": "src/codeCatalog/insertionSort/langs/insertion_sort.go",
    "source": "package algorithms\n\n// insertionSort — complete Go reference.\nfunc insertionSort(a []int) []int {\n\tarr := append([]int(nil), a...)\n\tfor i := 1; i < len(arr); i++ {\n\t\tkey := arr[i]\n\t\tj := i - 1\n\t\tfor j >= 0 && arr[j] > key {\n\t\t\tarr[j+1] = arr[j]\n\t\t\tj--\n\t\t}\n\t\tarr[j+1] = key\n\t}\n\treturn arr\n}\n",
    "sourceHash": "28913794b843db4482de5cb2d5fc395c281654e31fadc8b02d7e24827dc80227",
    "anchors": [
      {
        "id": "outer",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "shift",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "insert",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  }
]

export default docs
