// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/kruskal/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "kruskal.py",
    "language": "python",
    "title": "Kruskal MST (Python)",
    "sourceFile": "src/codeCatalog/kruskal/langs/kruskal.py",
    "source": "from typing import NamedTuple\n\n\nclass Edge(NamedTuple):\n    u: int\n    v: int\n    w: int\n\n\ndef kruskal(n: int, edges: list[Edge]) -> tuple[int, list[Edge]]:\n    \"\"\"Kruskal MST — complete Python reference (union-find with path compression).\"\"\"\n    parent = list(range(n))\n\n    def find(x: int) -> int:\n        if parent[x] != x:\n            parent[x] = find(parent[x])\n        return parent[x]\n\n    sorted_edges = sorted(edges, key=lambda e: e.w)\n    mst: list[Edge] = []\n    total = 0\n    for e in sorted_edges:\n        a = find(e.u)\n        b = find(e.v)\n        if a == b:\n            continue\n        parent[a] = b\n        mst.append(e)\n        total += e.w\n        if len(mst) == n - 1:\n            break\n    return total, mst\n",
    "sourceHash": "23b0c58cfb0f0b1aaa88cbebadabd568445f8104bdac6e666de153fc7757426d",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "find",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      },
      {
        "id": "union",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      }
    ]
  },
  {
    "documentId": "kruskal.cpp",
    "language": "cpp",
    "title": "Kruskal MST (C++)",
    "sourceFile": "src/codeCatalog/kruskal/langs/kruskal.cpp",
    "source": "// Kruskal MST — complete C++17 reference (union-find with path compression).\n#include <algorithm>\n#include <functional>\n#include <numeric>\n#include <utility>\n#include <vector>\n\nstruct Edge { int u, v; long long w; };\n\nstd::pair<long long, std::vector<Edge>> kruskal(int n, const std::vector<Edge>& edges) {\n    std::vector<int> parent(n);\n    std::iota(parent.begin(), parent.end(), 0);\n    std::function<int(int)> find = [&](int x) { return parent[x] == x ? x : parent[x] = find(parent[x]); };\n    std::vector<Edge> sorted = edges;\n    std::stable_sort(sorted.begin(), sorted.end(), [](const Edge& a, const Edge& b) { return a.w < b.w; });\n    std::vector<Edge> mst;\n    long long total = 0;\n    for (const Edge& e : sorted) {\n        int a = find(e.u);\n        int b = find(e.v);\n        if (a == b) continue;\n        parent[a] = b;\n        mst.push_back(e);\n        total += e.w;\n        if (static_cast<int>(mst.size()) == n - 1) break;\n    }\n    return {total, mst};\n}\n",
    "sourceHash": "74b491972b983a188cc4f54f8d57fe80fc0f62cc9518cd78302f8b9fdb68bab8",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "find",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "union",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      }
    ]
  },
  {
    "documentId": "kruskal.java",
    "language": "java",
    "title": "Kruskal MST (Java)",
    "sourceFile": "src/codeCatalog/kruskal/langs/Kruskal.java",
    "source": "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\n/** Kruskal MST — complete Java reference (union-find with path compression). */\npublic final class Kruskal {\n    public record Edge(int u, int v, long w) {}\n    public record Result(long total, List<Edge> mst) {}\n\n    private static int find(int[] parent, int x) {\n        return parent[x] == x ? x : (parent[x] = find(parent, parent[x]));\n    }\n\n    public static Result kruskal(int n, List<Edge> edges) {\n        int[] parent = new int[n];\n        for (int i = 0; i < n; i++) parent[i] = i;\n        List<Edge> sorted = new ArrayList<>(edges);\n        sorted.sort(Comparator.comparingLong(Edge::w));\n        List<Edge> mst = new ArrayList<>();\n        long total = 0;\n        for (Edge e : sorted) {\n            int a = find(parent, e.u());\n            int b = find(parent, e.v());\n            if (a == b) continue;\n            parent[a] = b;\n            mst.add(e);\n            total += e.w();\n            if (mst.size() == n - 1) break;\n        }\n        return new Result(total, mst);\n    }\n}\n",
    "sourceHash": "8961c9d3049b7cdce56f04583db89390f21a4c652ff2f0884e29cf835699f4f7",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "find",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "union",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      }
    ]
  },
  {
    "documentId": "kruskal.rs",
    "language": "rust",
    "title": "Kruskal MST (Rust)",
    "sourceFile": "src/codeCatalog/kruskal/langs/kruskal.rs",
    "source": "/// Kruskal MST — complete Rust reference (union-find with path compression).\n#[derive(Clone, Copy)]\npub struct Edge {\n    pub u: usize,\n    pub v: usize,\n    pub w: i64,\n}\n\npub fn kruskal(n: usize, edges: &[Edge]) -> (i64, Vec<Edge>) {\n    fn find(parent: &mut Vec<usize>, x: usize) -> usize {\n        if parent[x] != x {\n            let p = parent[x];\n            parent[x] = find(parent, p);\n        }\n        parent[x]\n    }\n    let mut parent: Vec<usize> = (0..n).collect();\n    let mut sorted = edges.to_vec();\n    sorted.sort_by_key(|e| e.w);\n    let mut mst: Vec<Edge> = Vec::new();\n    let mut total = 0;\n    for e in sorted {\n        let a = find(&mut parent, e.u);\n        let b = find(&mut parent, e.v);\n        if a == b {\n            continue;\n        }\n        parent[a] = b;\n        mst.push(e);\n        total += e.w;\n        if mst.len() == n - 1 {\n            break;\n        }\n    }\n    (total, mst)\n}\n",
    "sourceHash": "be3997ebfd8f10bb844623e4bdb2655fc323af127156537607dcfd014998ee5e",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "find",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 25,
          "endLine": 26
        }
      },
      {
        "id": "union",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      }
    ]
  },
  {
    "documentId": "kruskal.go",
    "language": "go",
    "title": "Kruskal MST (Go)",
    "sourceFile": "src/codeCatalog/kruskal/langs/kruskal.go",
    "source": "package algorithms\n\nimport \"sort\"\n\n// Edge is an undirected weighted edge.\ntype Edge struct{ U, V, W int }\n\n// kruskal — Kruskal MST with union-find (path compression), complete Go reference.\nfunc kruskal(n int, edges []Edge) (int, []Edge) {\n\tparent := make([]int, n)\n\tfor i := range parent {\n\t\tparent[i] = i\n\t}\n\tvar find func(x int) int\n\tfind = func(x int) int {\n\t\tif parent[x] != x {\n\t\t\tparent[x] = find(parent[x])\n\t\t}\n\t\treturn parent[x]\n\t}\n\tsorted := append([]Edge(nil), edges...)\n\tsort.SliceStable(sorted, func(i, j int) bool { return sorted[i].W < sorted[j].W })\n\tmst := []Edge{}\n\ttotal := 0\n\tfor _, e := range sorted {\n\t\ta := find(e.U)\n\t\tb := find(e.V)\n\t\tif a == b {\n\t\t\tcontinue\n\t\t}\n\t\tparent[a] = b\n\t\tmst = append(mst, e)\n\t\ttotal += e.W\n\t\tif len(mst) == n-1 {\n\t\t\tbreak\n\t\t}\n\t}\n\treturn total, mst\n}\n",
    "sourceHash": "f872d1cc30275fa52e5af41568330bca580561173f8eee4ecc11d2763a730e40",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "find",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 28,
          "endLine": 29
        }
      },
      {
        "id": "union",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      }
    ]
  }
]

export default docs
