// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/maxSubarrayDC/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "maxSubarrayDC.py",
    "language": "python",
    "title": "最大子数组分治 (Python)",
    "sourceFile": "src/codeCatalog/maxSubarrayDC/langs/max_subarray_dc.py",
    "source": "def max_subarray_dc(a: list[int]) -> int:\n    \"\"\"Max subarray divide-and-conquer — complete Python reference.\"\"\"\n    def solve(lo: int, hi: int) -> int:\n        if lo == hi:\n            return a[lo]\n        mid = (lo + hi) >> 1\n        left = solve(lo, mid)\n        right = solve(mid + 1, hi)\n        cross = crossing(lo, mid, hi)\n        return max(left, right, cross)\n\n    def crossing(lo: int, mid: int, hi: int) -> int:\n        left_sum = float(\"-inf\")\n        s = 0\n        for i in range(mid, lo - 1, -1):\n            s += a[i]\n            if s > left_sum:\n                left_sum = s\n        right_sum = float(\"-inf\")\n        s = 0\n        for i in range(mid + 1, hi + 1):\n            s += a[i]\n            if s > right_sum:\n                right_sum = s\n        return int(left_sum + right_sum)\n\n    if not a:\n        return 0\n    return solve(0, len(a) - 1)\n",
    "sourceHash": "9850627ef204c85bafa3f0bc82a95c9ace9f5b4caf23fc38024bebe6247cec0c",
    "anchors": [
      {
        "id": "base",
        "range": {
          "startLine": 4,
          "endLine": 5
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "cross",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "combine",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "empty",
        "range": {
          "startLine": 27,
          "endLine": 28
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      }
    ]
  },
  {
    "documentId": "maxSubarrayDC.cpp",
    "language": "cpp",
    "title": "最大子数组分治 (C++)",
    "sourceFile": "src/codeCatalog/maxSubarrayDC/langs/max_subarray_dc.cpp",
    "source": "// Max subarray divide-and-conquer — complete C++17 reference.\n#include <algorithm>\n#include <climits>\n#include <functional>\n#include <vector>\n\nlong long maxSubarrayDC(const std::vector<long long>& a) {\n    std::function<long long(int, int, int)> crossing;\n    std::function<long long(int, int)> solve = [&](int lo, int hi) -> long long {\n        if (lo == hi) return a[lo];\n        int mid = (lo + hi) >> 1;\n        long long left = solve(lo, mid);\n        long long right = solve(mid + 1, hi);\n        long long cross = crossing(lo, mid, hi);\n        return std::max({left, right, cross});\n    };\n    crossing = [&](int lo, int mid, int hi) -> long long {\n        long long leftSum = LLONG_MIN;\n        long long s = 0;\n        for (int i = mid; i >= lo; i--) {\n            s += a[i];\n            if (s > leftSum) leftSum = s;\n        }\n        long long rightSum = LLONG_MIN;\n        s = 0;\n        for (int i = mid + 1; i <= hi; i++) {\n            s += a[i];\n            if (s > rightSum) rightSum = s;\n        }\n        return leftSum + rightSum;\n    };\n    if (a.empty()) return 0;\n    return solve(0, static_cast<int>(a.size()) - 1);\n}\n",
    "sourceHash": "82b042a0a02fb2f697aaf34d8e07bafc97d729036f71afcee494332ff5b19671",
    "anchors": [
      {
        "id": "base",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "cross",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "combine",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "empty",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      }
    ]
  },
  {
    "documentId": "maxSubarrayDC.java",
    "language": "java",
    "title": "最大子数组分治 (Java)",
    "sourceFile": "src/codeCatalog/maxSubarrayDC/langs/MaxSubarrayDC.java",
    "source": "/** Max subarray divide-and-conquer — complete Java reference. */\npublic final class MaxSubarrayDC {\n    public static long maxSubarrayDC(long[] a) {\n        if (a.length == 0) return 0;\n        return solve(a, 0, a.length - 1);\n    }\n\n    private static long solve(long[] a, int lo, int hi) {\n        if (lo == hi) return a[lo];\n        int mid = (lo + hi) >> 1;\n        long left = solve(a, lo, mid);\n        long right = solve(a, mid + 1, hi);\n        long cross = crossing(a, lo, mid, hi);\n        return Math.max(left, Math.max(right, cross));\n    }\n\n    private static long crossing(long[] a, int lo, int mid, int hi) {\n        long leftSum = Long.MIN_VALUE;\n        long s = 0;\n        for (int i = mid; i >= lo; i--) {\n            s += a[i];\n            if (s > leftSum) leftSum = s;\n        }\n        long rightSum = Long.MIN_VALUE;\n        s = 0;\n        for (int i = mid + 1; i <= hi; i++) {\n            s += a[i];\n            if (s > rightSum) rightSum = s;\n        }\n        return leftSum + rightSum;\n    }\n}\n",
    "sourceHash": "ee234419faedfa99e2469fc6decb6ad37880b16872bdb250cb51087705b4c62a",
    "anchors": [
      {
        "id": "empty",
        "range": {
          "startLine": 4,
          "endLine": 4
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "base",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "cross",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "combine",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "maxSubarrayDC.rs",
    "language": "rust",
    "title": "最大子数组分治 (Rust)",
    "sourceFile": "src/codeCatalog/maxSubarrayDC/langs/max_subarray_dc.rs",
    "source": "/// Max subarray divide-and-conquer — complete Rust reference.\npub fn max_subarray_dc(a: &[i64]) -> i64 {\n    fn solve(a: &[i64], lo: usize, hi: usize) -> i64 {\n        if lo == hi {\n            return a[lo];\n        }\n        let mid = (lo + hi) >> 1;\n        let left = solve(a, lo, mid);\n        let right = solve(a, mid + 1, hi);\n        let cross = crossing(a, lo, mid, hi);\n        left.max(right).max(cross)\n    }\n    fn crossing(a: &[i64], lo: usize, mid: usize, hi: usize) -> i64 {\n        let mut left_sum = i64::MIN;\n        let mut s = 0;\n        for i in (lo..=mid).rev() {\n            s += a[i];\n            if s > left_sum { left_sum = s; }\n        }\n        let mut right_sum = i64::MIN;\n        s = 0;\n        for i in mid + 1..=hi {\n            s += a[i];\n            if s > right_sum { right_sum = s; }\n        }\n        left_sum + right_sum\n    }\n    if a.is_empty() {\n        return 0;\n    }\n    solve(a, 0, a.len() - 1)\n}\n",
    "sourceHash": "2302a272d501ae32e58b21020e8adb98b09d2085e30823e3e5a52d3f8145ea40",
    "anchors": [
      {
        "id": "base",
        "range": {
          "startLine": 4,
          "endLine": 5
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "cross",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "combine",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "empty",
        "range": {
          "startLine": 28,
          "endLine": 29
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      }
    ]
  },
  {
    "documentId": "maxSubarrayDC.go",
    "language": "go",
    "title": "最大子数组分治 (Go)",
    "sourceFile": "src/codeCatalog/maxSubarrayDC/langs/max_subarray_dc.go",
    "source": "package algorithms\n\nimport \"math\"\n\n// maxSubarrayDC — max subarray divide-and-conquer, complete Go reference.\nfunc maxSubarrayDC(a []int) int {\n\tvar crossing func(lo, mid, hi int) int\n\tvar solve func(lo, hi int) int\n\tsolve = func(lo, hi int) int {\n\t\tif lo == hi {\n\t\t\treturn a[lo]\n\t\t}\n\t\tmid := (lo + hi) >> 1\n\t\tleft := solve(lo, mid)\n\t\tright := solve(mid+1, hi)\n\t\tcross := crossing(lo, mid, hi)\n\t\treturn max(left, right, cross)\n\t}\n\tcrossing = func(lo, mid, hi int) int {\n\t\tleftSum := math.MinInt\n\t\ts := 0\n\t\tfor i := mid; i >= lo; i-- {\n\t\t\ts += a[i]\n\t\t\tif s > leftSum {\n\t\t\t\tleftSum = s\n\t\t\t}\n\t\t}\n\t\trightSum := math.MinInt\n\t\ts = 0\n\t\tfor i := mid + 1; i <= hi; i++ {\n\t\t\ts += a[i]\n\t\t\tif s > rightSum {\n\t\t\t\trightSum = s\n\t\t\t}\n\t\t}\n\t\treturn leftSum + rightSum\n\t}\n\tif len(a) == 0 {\n\t\treturn 0\n\t}\n\treturn solve(0, len(a)-1)\n}\n",
    "sourceHash": "62ff24c119cab60baf672bde9d44cdb9ec05d121fad9df592fb22069d1a42004",
    "anchors": [
      {
        "id": "base",
        "range": {
          "startLine": 10,
          "endLine": 11
        }
      },
      {
        "id": "divide",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "cross",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "combine",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "empty",
        "range": {
          "startLine": 38,
          "endLine": 39
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 41,
          "endLine": 41
        }
      }
    ]
  }
]

export default docs
