// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/kmp/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "kmp.py",
    "language": "python",
    "title": "KMP (Python)",
    "sourceFile": "src/codeCatalog/kmp/langs/kmp.py",
    "source": "def kmp_search(text: str, pattern: str) -> list[int]:\n    \"\"\"KMP string matching — complete Python reference.\"\"\"\n    hits: list[int] = []\n    if not pattern:\n        return [0]\n    lps = build_lps(pattern)\n    i = 0\n    j = 0\n    while i < len(text):\n        if text[i] == pattern[j]:\n            i += 1\n            j += 1\n            if j == len(pattern):\n                hits.append(i - j)\n                j = lps[j - 1]\n        elif j > 0:\n            j = lps[j - 1]\n        else:\n            i += 1\n    return hits\n\n\ndef build_lps(pattern: str) -> list[int]:\n    lps = [0] * len(pattern)\n    length = 0\n    i = 1\n    while i < len(pattern):\n        if pattern[i] == pattern[length]:\n            length += 1\n            lps[i] = length\n            i += 1\n        elif length > 0:\n            length = lps[length - 1]\n        else:\n            lps[i] = 0\n            i += 1\n    return lps\n",
    "sourceHash": "b3115b2740fa1e26a7deb0250d6e72866c1d01432e53304507289a7dcb9a3ef2",
    "anchors": [
      {
        "id": "emptyPattern",
        "range": {
          "startLine": 4,
          "endLine": 5
        }
      },
      {
        "id": "buildLps",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "match",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "hit",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "fallback",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "fallbackWrite",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "advance",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "lpsCompare",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      },
      {
        "id": "lpsExtend",
        "range": {
          "startLine": 29,
          "endLine": 30
        }
      },
      {
        "id": "lpsFallbackCond",
        "range": {
          "startLine": 32,
          "endLine": 32
        }
      },
      {
        "id": "lpsFallback",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "lpsZero",
        "range": {
          "startLine": 35,
          "endLine": 36
        }
      },
      {
        "id": "lpsReturn",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      }
    ]
  },
  {
    "documentId": "kmp.cpp",
    "language": "cpp",
    "title": "KMP (C++)",
    "sourceFile": "src/codeCatalog/kmp/langs/kmp.cpp",
    "source": "// KMP string matching — complete C++ reference.\n#include <string>\n#include <vector>\n\nstd::vector<int> buildLps(const std::string& pattern);\n\nstd::vector<int> kmpSearch(const std::string& text, const std::string& pattern) {\n  std::vector<int> hits;\n  if (pattern.empty()) return {0};\n  const std::vector<int> lps = buildLps(pattern);\n  size_t i = 0;\n  size_t j = 0;\n  while (i < text.size()) {\n    if (text[i] == pattern[j]) {\n      i++;\n      j++;\n      if (j == pattern.size()) {\n        hits.push_back(static_cast<int>(i - j));\n        j = lps[j - 1];\n      }\n    } else if (j > 0) {\n      j = lps[j - 1];\n    } else {\n      i++;\n    }\n  }\n  return hits;\n}\n\nstd::vector<int> buildLps(const std::string& pattern) {\n  std::vector<int> lps(pattern.size(), 0);\n  int len = 0;\n  size_t i = 1;\n  while (i < pattern.size()) {\n    if (pattern[i] == pattern[len]) {\n      len++;\n      lps[i] = len;\n      i++;\n    } else if (len > 0) {\n      len = lps[len - 1];\n    } else {\n      lps[i] = 0;\n      i++;\n    }\n  }\n  return lps;\n}\n",
    "sourceHash": "786ea3504ddeb57af776589d74e1ace5849172b3fc5a75f8b1d3abe9092cb895",
    "anchors": [
      {
        "id": "emptyPattern",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "buildLps",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "match",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "hit",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "fallback",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "fallbackWrite",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "advance",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "lpsCompare",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "lpsExtend",
        "range": {
          "startLine": 36,
          "endLine": 37
        }
      },
      {
        "id": "lpsFallbackCond",
        "range": {
          "startLine": 39,
          "endLine": 39
        }
      },
      {
        "id": "lpsFallback",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      },
      {
        "id": "lpsZero",
        "range": {
          "startLine": 42,
          "endLine": 43
        }
      },
      {
        "id": "lpsReturn",
        "range": {
          "startLine": 46,
          "endLine": 46
        }
      }
    ]
  },
  {
    "documentId": "kmp.java",
    "language": "java",
    "title": "KMP (Java)",
    "sourceFile": "src/codeCatalog/kmp/langs/Kmp.java",
    "source": "import java.util.ArrayList;\nimport java.util.List;\n\n/** KMP string matching — complete Java reference. */\npublic final class Kmp {\n  public static List<Integer> kmpSearch(String text, String pattern) {\n    List<Integer> hits = new ArrayList<>();\n    if (pattern.isEmpty()) return List.of(0);\n    int[] lps = buildLps(pattern);\n    int i = 0;\n    int j = 0;\n    while (i < text.length()) {\n      if (text.charAt(i) == pattern.charAt(j)) {\n        i++;\n        j++;\n        if (j == pattern.length()) {\n          hits.add(i - j);\n          j = lps[j - 1];\n        }\n      } else if (j > 0) {\n        j = lps[j - 1];\n      } else {\n        i++;\n      }\n    }\n    return hits;\n  }\n\n  static int[] buildLps(String pattern) {\n    int[] lps = new int[pattern.length()];\n    int len = 0;\n    int i = 1;\n    while (i < pattern.length()) {\n      if (pattern.charAt(i) == pattern.charAt(len)) {\n        len++;\n        lps[i] = len;\n        i++;\n      } else if (len > 0) {\n        len = lps[len - 1];\n      } else {\n        lps[i] = 0;\n        i++;\n      }\n    }\n    return lps;\n  }\n}\n",
    "sourceHash": "cc917dcf4b086b4ece437d357051434bf523bfbd31b448be1777f67ed04df931",
    "anchors": [
      {
        "id": "emptyPattern",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "buildLps",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "match",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "hit",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "fallback",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "fallbackWrite",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "advance",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "lpsCompare",
        "range": {
          "startLine": 34,
          "endLine": 34
        }
      },
      {
        "id": "lpsExtend",
        "range": {
          "startLine": 35,
          "endLine": 36
        }
      },
      {
        "id": "lpsFallbackCond",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      },
      {
        "id": "lpsFallback",
        "range": {
          "startLine": 39,
          "endLine": 39
        }
      },
      {
        "id": "lpsZero",
        "range": {
          "startLine": 41,
          "endLine": 42
        }
      },
      {
        "id": "lpsReturn",
        "range": {
          "startLine": 45,
          "endLine": 45
        }
      }
    ]
  },
  {
    "documentId": "kmp.rs",
    "language": "rust",
    "title": "KMP (Rust)",
    "sourceFile": "src/codeCatalog/kmp/langs/kmp.rs",
    "source": "/// KMP string matching — complete Rust reference.\npub fn kmp_search(text: &str, pattern: &str) -> Vec<usize> {\n    let (t, p): (Vec<char>, Vec<char>) = (text.chars().collect(), pattern.chars().collect());\n    let mut hits: Vec<usize> = Vec::new();\n    if p.is_empty() {\n        return vec![0];\n    }\n    let lps = build_lps(&p);\n    let mut i = 0;\n    let mut j = 0;\n    while i < t.len() {\n        if t[i] == p[j] {\n            i += 1;\n            j += 1;\n            if j == p.len() {\n                hits.push(i - j);\n                j = lps[j - 1];\n            }\n        } else if j > 0 {\n            j = lps[j - 1];\n        } else {\n            i += 1;\n        }\n    }\n    hits\n}\n\nfn build_lps(p: &[char]) -> Vec<usize> {\n    let mut lps = vec![0; p.len()];\n    let mut len = 0;\n    let mut i = 1;\n    while i < p.len() {\n        if p[i] == p[len] {\n            len += 1;\n            lps[i] = len;\n            i += 1;\n        } else if len > 0 {\n            len = lps[len - 1];\n        } else {\n            lps[i] = 0;\n            i += 1;\n        }\n    }\n    lps\n}\n",
    "sourceHash": "2cb9e3642ccb6d643bbe806cac520d0a2cc9a8e75aa3c793160b7655b7d6641a",
    "anchors": [
      {
        "id": "emptyPattern",
        "range": {
          "startLine": 5,
          "endLine": 6
        }
      },
      {
        "id": "buildLps",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "match",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "hit",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "fallback",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "fallbackWrite",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "advance",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "lpsCompare",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "lpsExtend",
        "range": {
          "startLine": 34,
          "endLine": 35
        }
      },
      {
        "id": "lpsFallbackCond",
        "range": {
          "startLine": 37,
          "endLine": 37
        }
      },
      {
        "id": "lpsFallback",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      },
      {
        "id": "lpsZero",
        "range": {
          "startLine": 40,
          "endLine": 41
        }
      },
      {
        "id": "lpsReturn",
        "range": {
          "startLine": 44,
          "endLine": 44
        }
      }
    ]
  },
  {
    "documentId": "kmp.go",
    "language": "go",
    "title": "KMP (Go)",
    "sourceFile": "src/codeCatalog/kmp/langs/kmp.go",
    "source": "// KMP string matching — complete Go reference.\npackage algorithms\n\n// kmpSearch returns every start index where pattern occurs in text.\nfunc kmpSearch(text, pattern string) []int {\n\thits := []int{}\n\tif len(pattern) == 0 {\n\t\treturn []int{0}\n\t}\n\tlps := buildLps(pattern)\n\ti := 0\n\tj := 0\n\tfor i < len(text) {\n\t\tif text[i] == pattern[j] {\n\t\t\ti++\n\t\t\tj++\n\t\t\tif j == len(pattern) {\n\t\t\t\thits = append(hits, i-j)\n\t\t\t\tj = lps[j-1]\n\t\t\t}\n\t\t} else if j > 0 {\n\t\t\tj = lps[j-1]\n\t\t} else {\n\t\t\ti++\n\t\t}\n\t}\n\treturn hits\n}\n\nfunc buildLps(pattern string) []int {\n\tlps := make([]int, len(pattern))\n\tlength := 0\n\ti := 1\n\tfor i < len(pattern) {\n\t\tif pattern[i] == pattern[length] {\n\t\t\tlength++\n\t\t\tlps[i] = length\n\t\t\ti++\n\t\t} else if length > 0 {\n\t\t\tlength = lps[length-1]\n\t\t} else {\n\t\t\tlps[i] = 0\n\t\t\ti++\n\t\t}\n\t}\n\treturn lps\n}\n",
    "sourceHash": "d41496c8edb065192c6f282a5713921cb53e5fd53ba4785131cdba680b8d8154",
    "anchors": [
      {
        "id": "emptyPattern",
        "range": {
          "startLine": 7,
          "endLine": 8
        }
      },
      {
        "id": "buildLps",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "match",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "hit",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "fallback",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "fallbackWrite",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "advance",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "lpsCompare",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "lpsExtend",
        "range": {
          "startLine": 36,
          "endLine": 37
        }
      },
      {
        "id": "lpsFallbackCond",
        "range": {
          "startLine": 39,
          "endLine": 39
        }
      },
      {
        "id": "lpsFallback",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      },
      {
        "id": "lpsZero",
        "range": {
          "startLine": 42,
          "endLine": 43
        }
      },
      {
        "id": "lpsReturn",
        "range": {
          "startLine": 46,
          "endLine": 46
        }
      }
    ]
  }
]

export default docs
