// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/huffman/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "huffman.py",
    "language": "python",
    "title": "Huffman (Python)",
    "sourceFile": "src/codeCatalog/huffman/langs/huffman.py",
    "source": "from dataclasses import dataclass\nfrom typing import Optional\n\n\n@dataclass\nclass HNode:\n    freq: int\n    ch: Optional[str] = None\n    left: Optional[\"HNode\"] = None\n    right: Optional[\"HNode\"] = None\n\n\ndef huffman(symbols: list[str], freqs: list[int]) -> Optional[HNode]:\n    \"\"\"Huffman coding — complete Python reference.\"\"\"\n    nodes = [HNode(freqs[i], ch) for i, ch in enumerate(symbols)]\n    if not nodes:\n        return None\n    while len(nodes) > 1:\n        nodes.sort(key=lambda x: x.freq)\n        a = nodes.pop(0)\n        b = nodes.pop(0)\n        nodes.append(HNode(a.freq + b.freq, None, a, b))\n    return nodes[0]\n",
    "sourceHash": "6bbc731b88b25376df70c9d01ec0a7339747e179b4733d92dfb631f0048bdc52",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "sort",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "merge",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      }
    ]
  },
  {
    "documentId": "huffman.cpp",
    "language": "cpp",
    "title": "Huffman (C++)",
    "sourceFile": "src/codeCatalog/huffman/langs/huffman.cpp",
    "source": "// Huffman coding — complete C++17 reference.\n#include <algorithm>\n#include <memory>\n#include <string>\n#include <vector>\n\nstruct HNode {\n    std::string ch;\n    long long freq;\n    std::shared_ptr<HNode> left, right;\n};\nusing Node = std::shared_ptr<HNode>;\n\nNode huffman(const std::vector<std::string>& symbols, const std::vector<long long>& freqs) {\n    std::vector<Node> nodes;\n    for (size_t i = 0; i < symbols.size(); i++) nodes.push_back(std::make_shared<HNode>(HNode{symbols[i], freqs[i], nullptr, nullptr}));\n    if (nodes.empty()) return nullptr;\n    while (nodes.size() > 1) {\n        std::stable_sort(nodes.begin(), nodes.end(), [](const Node& a, const Node& b) { return a->freq < b->freq; });\n        Node a = nodes.front();\n        nodes.erase(nodes.begin());\n        Node b = nodes.front();\n        nodes.erase(nodes.begin());\n        nodes.push_back(std::make_shared<HNode>(HNode{\"\", a->freq + b->freq, a, b}));\n    }\n    return nodes[0];\n}\n",
    "sourceHash": "3acf413ccaa4e84f89de26133a60e9ffdbc171d8c99fa681ae86c719fa4d7979",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "sort",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      },
      {
        "id": "merge",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  },
  {
    "documentId": "huffman.java",
    "language": "java",
    "title": "Huffman (Java)",
    "sourceFile": "src/codeCatalog/huffman/langs/Huffman.java",
    "source": "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\n/** Huffman coding — complete Java reference. */\npublic final class Huffman {\n    public static final class HNode {\n        final String ch;\n        final long freq;\n        final HNode left, right;\n\n        HNode(String ch, long freq, HNode left, HNode right) {\n            this.ch = ch;\n            this.freq = freq;\n            this.left = left;\n            this.right = right;\n        }\n    }\n\n    public static HNode huffman(String[] symbols, long[] freqs) {\n        List<HNode> nodes = new ArrayList<>();\n        for (int i = 0; i < symbols.length; i++) nodes.add(new HNode(symbols[i], freqs[i], null, null));\n        if (nodes.isEmpty()) return null;\n        while (nodes.size() > 1) {\n            nodes.sort(Comparator.comparingLong(x -> x.freq));\n            HNode a = nodes.remove(0);\n            HNode b = nodes.remove(0);\n            nodes.add(new HNode(null, a.freq + b.freq, a, b));\n        }\n        return nodes.get(0);\n    }\n}\n",
    "sourceHash": "10343cd1d8bb52be4932c3bc2ad9d890c0f0e68d10c23d724548826c8340f0c8",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "sort",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "merge",
        "range": {
          "startLine": 28,
          "endLine": 28
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      }
    ]
  },
  {
    "documentId": "huffman.rs",
    "language": "rust",
    "title": "Huffman (Rust)",
    "sourceFile": "src/codeCatalog/huffman/langs/huffman.rs",
    "source": "/// Huffman coding — complete Rust reference.\npub struct HNode {\n    pub ch: Option<String>,\n    pub freq: u64,\n    pub left: Option<Box<HNode>>,\n    pub right: Option<Box<HNode>>,\n}\n\npub fn huffman(symbols: &[String], freqs: &[u64]) -> Option<Box<HNode>> {\n    let mut nodes: Vec<Box<HNode>> = symbols.iter().zip(freqs).map(|(ch, &freq)| Box::new(HNode { ch: Some(ch.clone()), freq, left: None, right: None })).collect();\n    if nodes.is_empty() {\n        return None;\n    }\n    while nodes.len() > 1 {\n        nodes.sort_by_key(|x| x.freq);\n        let a = nodes.remove(0);\n        let b = nodes.remove(0);\n        nodes.push(Box::new(HNode { ch: None, freq: a.freq + b.freq, left: Some(a), right: Some(b) }));\n    }\n    nodes.pop()\n}\n",
    "sourceHash": "5c22b4f2374e2a57928cc1b8ffa57a6b60bf16b79ade8c7ae9b849c0a26c987d",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "sort",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "merge",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "huffman.go",
    "language": "go",
    "title": "Huffman (Go)",
    "sourceFile": "src/codeCatalog/huffman/langs/huffman.go",
    "source": "package algorithms\n\nimport \"sort\"\n\n// HNode is a Huffman tree node; leaves carry a symbol.\ntype HNode struct {\n\tCh          string\n\tFreq        int\n\tLeft, Right *HNode\n}\n\n// huffman — Huffman coding, complete Go reference.\nfunc huffman(symbols []string, freqs []int) *HNode {\n\tnodes := make([]*HNode, len(symbols))\n\tfor i, ch := range symbols {\n\t\tnodes[i] = &HNode{Ch: ch, Freq: freqs[i]}\n\t}\n\tif len(nodes) == 0 {\n\t\treturn nil\n\t}\n\tfor len(nodes) > 1 {\n\t\tsort.SliceStable(nodes, func(i, j int) bool { return nodes[i].Freq < nodes[j].Freq })\n\t\ta, b := nodes[0], nodes[1]\n\t\tnodes = nodes[2:]\n\t\tnodes = append(nodes, &HNode{Freq: a.Freq + b.Freq, Left: a, Right: b})\n\t}\n\treturn nodes[0]\n}\n",
    "sourceHash": "44ea6374eeeda3517d6baa6f2209cc79c9c6225585a94404db18125eeadbbe02",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 15,
          "endLine": 17
        }
      },
      {
        "id": "sort",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "merge",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      }
    ]
  }
]

export default docs
