// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/activitySelection/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "activitySelection.py",
    "language": "python",
    "title": "活动选择 (Python)",
    "sourceFile": "src/codeCatalog/activitySelection/langs/activity_selection.py",
    "source": "from typing import NamedTuple\n\n\nclass Activity(NamedTuple):\n    id: str\n    start: int\n    finish: int\n\n\ndef activity_selection(activities: list[Activity]) -> list[str]:\n    \"\"\"Activity selection (greedy by finish) — complete Python reference.\"\"\"\n    ordered = sorted(activities, key=lambda a: a.finish)\n    picked: list[str] = []\n    last_finish = float(\"-inf\")\n    for act in ordered:\n        if act.start >= last_finish:\n            picked.append(act.id)\n            last_finish = act.finish\n    return picked\n",
    "sourceHash": "9d02b08d6021322eb3da1ca00aed44d9f2289bc2a283f223cbaa113059462537",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 19,
          "endLine": 19
        }
      }
    ]
  },
  {
    "documentId": "activitySelection.cpp",
    "language": "cpp",
    "title": "活动选择 (C++)",
    "sourceFile": "src/codeCatalog/activitySelection/langs/activity_selection.cpp",
    "source": "// Activity selection (greedy by finish) — complete C++17 reference.\n#include <algorithm>\n#include <limits>\n#include <string>\n#include <vector>\n\nstruct Activity { std::string id; double start, finish; };\n\nstd::vector<std::string> activitySelection(const std::vector<Activity>& activities) {\n    std::vector<Activity> sorted = activities;\n    std::stable_sort(sorted.begin(), sorted.end(), [](const Activity& a, const Activity& b) { return a.finish < b.finish; });\n    std::vector<std::string> picked;\n    double lastFinish = -std::numeric_limits<double>::infinity();\n    for (const Activity& act : sorted) {\n        if (act.start >= lastFinish) {\n            picked.push_back(act.id);\n            lastFinish = act.finish;\n        }\n    }\n    return picked;\n}\n",
    "sourceHash": "04bed5bedf2bc8e749b5065ef2a477b45e90c711ae75379bffdc4a5022310677",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "activitySelection.java",
    "language": "java",
    "title": "活动选择 (Java)",
    "sourceFile": "src/codeCatalog/activitySelection/langs/ActivitySelection.java",
    "source": "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\n/** Activity selection (greedy by finish) — complete Java reference. */\npublic final class ActivitySelection {\n    public record Activity(String id, double start, double finish) {}\n\n    public static List<String> activitySelection(List<Activity> activities) {\n        List<Activity> sorted = new ArrayList<>(activities);\n        sorted.sort(Comparator.comparingDouble(Activity::finish));\n        List<String> picked = new ArrayList<>();\n        double lastFinish = Double.NEGATIVE_INFINITY;\n        for (Activity act : sorted) {\n            if (act.start() >= lastFinish) {\n                picked.add(act.id());\n                lastFinish = act.finish();\n            }\n        }\n        return picked;\n    }\n}\n",
    "sourceHash": "3be7c3bdd1bf2485d443b5af0a1359b4f7d86569969c36bf4b268f48b04ec555",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "activitySelection.rs",
    "language": "rust",
    "title": "活动选择 (Rust)",
    "sourceFile": "src/codeCatalog/activitySelection/langs/activity_selection.rs",
    "source": "/// Activity selection (greedy by finish) — complete Rust reference.\n#[derive(Clone)]\npub struct Activity {\n    pub id: String,\n    pub start: f64,\n    pub finish: f64,\n}\n\npub fn activity_selection(activities: &[Activity]) -> Vec<String> {\n    let mut sorted = activities.to_vec();\n    sorted.sort_by(|a, b| a.finish.total_cmp(&b.finish));\n    let mut picked: Vec<String> = Vec::new();\n    let mut last_finish = f64::NEG_INFINITY;\n    for act in &sorted {\n        if act.start >= last_finish {\n            picked.push(act.id.clone());\n            last_finish = act.finish;\n        }\n    }\n    picked\n}\n",
    "sourceHash": "65a0241497aa5f6b9f2a75a9d7befb0fad54e327bfafcf1efa36596b280d1cbb",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      }
    ]
  },
  {
    "documentId": "activitySelection.go",
    "language": "go",
    "title": "活动选择 (Go)",
    "sourceFile": "src/codeCatalog/activitySelection/langs/activity_selection.go",
    "source": "package algorithms\n\nimport (\n\t\"math\"\n\t\"sort\"\n)\n\n// Activity is a half-open interval [Start, Finish).\ntype Activity struct {\n\tID            string\n\tStart, Finish float64\n}\n\n// activitySelection — greedy by finish time, complete Go reference.\nfunc activitySelection(activities []Activity) []string {\n\tsorted := append([]Activity(nil), activities...)\n\tsort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Finish < sorted[j].Finish })\n\tpicked := []string{}\n\tlastFinish := math.Inf(-1)\n\tfor _, act := range sorted {\n\t\tif act.Start >= lastFinish {\n\t\t\tpicked = append(picked, act.ID)\n\t\t\tlastFinish = act.Finish\n\t\t}\n\t}\n\treturn picked\n}\n",
    "sourceHash": "d741bafcfb538404935f9f5e7f835e1f4bd912dfca189b9edcf437bfff49ae80",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      }
    ]
  }
]

export default docs
