// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/greedy/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.greedy.py",
    "language": "python",
    "title": "0-1 背包贪心密度 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/greedy/langs/knapsack_greedy.py",
    "source": "def knapsack_greedy_by_density(weights: list[int], values: list[int], W: int) -> tuple[int, list[int]]:\n    \"\"\"0-1 knapsack greedy-by-density (NOT optimal) — complete Python reference. Returns (value, selected).\"\"\"\n    order = sorted(range(len(weights)), key=lambda i: -values[i] / weights[i])\n    rem = W\n    value = 0\n    selected: list[int] = []\n    for i in order:\n        if weights[i] <= rem:\n            rem -= weights[i]\n            value += values[i]\n            selected.append(i)\n    return value, selected\n",
    "sourceHash": "4c3943d9e6a6b9ef1cc25838a4b7425d932c5c2031276d48a9bd8697f756b7c6",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      }
    ]
  },
  {
    "documentId": "knapsack.greedy.cpp",
    "language": "cpp",
    "title": "0-1 背包贪心密度 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/greedy/langs/knapsack_greedy.cpp",
    "source": "// 0-1 knapsack greedy-by-density (NOT optimal) — complete C++17 reference.\n#include <algorithm>\n#include <numeric>\n#include <utility>\n#include <vector>\n\nstd::pair<long long, std::vector<int>> knapsackGreedyByDensity(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    std::vector<int> order(weights.size());\n    std::iota(order.begin(), order.end(), 0);\n    std::stable_sort(order.begin(), order.end(), [&](int a, int b) { return 1.0 * values[a] / weights[a] > 1.0 * values[b] / weights[b]; });\n    int rem = W;\n    long long value = 0;\n    std::vector<int> selected;\n    for (int i : order) {\n        if (weights[i] <= rem) {\n            rem -= weights[i];\n            value += values[i];\n            selected.push_back(i);\n        }\n    }\n    return {value, selected};\n}\n",
    "sourceHash": "99e9d02487b0b0307e31e2b6584ff4aa7114f26517988934f5765c4eff59a40d",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      }
    ]
  },
  {
    "documentId": "knapsack.greedy.java",
    "language": "java",
    "title": "0-1 背包贪心密度 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/greedy/langs/KnapsackGreedy.java",
    "source": "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\n/** 0-1 knapsack greedy-by-density (NOT optimal) — complete Java reference. */\npublic final class KnapsackGreedy {\n    public record Result(long value, List<Integer> selected) {}\n\n    public static Result knapsackGreedyByDensity(int[] weights, long[] values, int W) {\n        List<Integer> order = new ArrayList<>();\n        for (int i = 0; i < weights.length; i++) order.add(i);\n        order.sort(Comparator.comparingDouble(i -> -(double) values[i] / weights[i]));\n        int rem = W;\n        long value = 0;\n        List<Integer> selected = new ArrayList<>();\n        for (int i : order) {\n            if (weights[i] <= rem) {\n                rem -= weights[i];\n                value += values[i];\n                selected.add(i);\n            }\n        }\n        return new Result(value, selected);\n    }\n}\n",
    "sourceHash": "9e2b4626a575663605285359e2826c917eebcd3afa7e9e9f5613e5b64bd8c5ab",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      }
    ]
  },
  {
    "documentId": "knapsack.greedy.rs",
    "language": "rust",
    "title": "0-1 背包贪心密度 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/greedy/langs/knapsack_greedy.rs",
    "source": "/// 0-1 knapsack greedy-by-density (NOT optimal) — complete Rust reference (capacity W is `cap`).\npub fn knapsack_greedy_by_density(weights: &[usize], values: &[i64], cap: usize) -> (i64, Vec<usize>) {\n    let density = |i: usize| values[i] as f64 / weights[i] as f64;\n    let mut order: Vec<usize> = (0..weights.len()).collect();\n    order.sort_by(|&a, &b| density(b).total_cmp(&density(a)));\n    let mut rem = cap;\n    let mut value = 0;\n    let mut selected: Vec<usize> = Vec::new();\n    for i in order {\n        if weights[i] <= rem {\n            rem -= weights[i];\n            value += values[i];\n            selected.push(i);\n        }\n    }\n    (value, selected)\n}\n",
    "sourceHash": "f93e3092332b9664b985abe372c5cc0d7faa8ae0c3486d81b5b4ea458dbd8d3f",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      }
    ]
  },
  {
    "documentId": "knapsack.greedy.go",
    "language": "go",
    "title": "0-1 背包贪心密度 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/greedy/langs/knapsack_greedy.go",
    "source": "package algorithms\n\nimport \"sort\"\n\n// knapsackGreedyByDensity — 0-1 knapsack greedy by density (NOT optimal), complete Go reference.\nfunc knapsackGreedyByDensity(weights, values []int, W int) (int, []int) {\n\torder := make([]int, len(weights))\n\tfor i := range order {\n\t\torder[i] = i\n\t}\n\tdensity := func(i int) float64 { return float64(values[i]) / float64(weights[i]) }\n\tsort.SliceStable(order, func(a, b int) bool { return density(order[a]) > density(order[b]) })\n\trem := W\n\tvalue := 0\n\tselected := []int{}\n\tfor _, i := range order {\n\t\tif weights[i] <= rem {\n\t\t\trem -= weights[i]\n\t\t\tvalue += values[i]\n\t\t\tselected = append(selected, i)\n\t\t}\n\t}\n\treturn value, selected\n}\n",
    "sourceHash": "87546d309f4d994ee43089126fafdc53bde0c85a323ac89054510f77d05760ce",
    "anchors": [
      {
        "id": "sort",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "check",
        "range": {
          "startLine": 17,
          "endLine": 17
        }
      },
      {
        "id": "pick",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      }
    ]
  }
]

export default docs
