// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/nQueens/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "nQueens.py",
    "language": "python",
    "title": "N 皇后 (Python)",
    "sourceFile": "src/codeCatalog/nQueens/langs/n_queens.py",
    "source": "def solve_n_queens(n: int) -> list[list[int]]:\n    \"\"\"N-Queens backtracking — complete Python reference.\"\"\"\n    solutions: list[list[int]] = []\n    cols = [-1] * n\n\n    def is_safe(row: int, col: int) -> bool:\n        for r in range(row):\n            c = cols[r]\n            if c == col or abs(c - col) == row - r:\n                return False\n        return True\n\n    def dfs(row: int) -> None:\n        if row == n:\n            solutions.append(cols[:])\n            return\n        for col in range(n):\n            if not is_safe(row, col):\n                continue\n            cols[row] = col\n            dfs(row + 1)\n            cols[row] = -1\n\n    dfs(0)\n    return solutions\n",
    "sourceHash": "33e172f54ac2235db58df5b920a59338b238893455263962abfe593142808179",
    "anchors": [
      {
        "id": "conflict",
        "range": {
          "startLine": 9,
          "endLine": 10
        }
      },
      {
        "id": "call",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "solution",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "place",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "backtrack",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      }
    ]
  },
  {
    "documentId": "nQueens.cpp",
    "language": "cpp",
    "title": "N 皇后 (C++)",
    "sourceFile": "src/codeCatalog/nQueens/langs/n_queens.cpp",
    "source": "// N-Queens backtracking — complete C++17 reference.\n#include <cstdlib>\n#include <functional>\n#include <vector>\n\nstd::vector<std::vector<int>> solveNQueens(int n) {\n    std::vector<std::vector<int>> solutions;\n    std::vector<int> cols(n, -1);\n    auto isSafe = [&](int row, int col) -> bool {\n        for (int r = 0; r < row; r++) {\n            int c = cols[r];\n            if (c == col || std::abs(c - col) == row - r) return false;\n        }\n        return true;\n    };\n    std::function<void(int)> dfs = [&](int row) {\n        if (row == n) {\n            solutions.push_back(cols);\n            return;\n        }\n        for (int col = 0; col < n; col++) {\n            if (!isSafe(row, col)) continue;\n            cols[row] = col;\n            dfs(row + 1);\n            cols[row] = -1;\n        }\n    };\n    dfs(0);\n    return solutions;\n}\n",
    "sourceHash": "09bc8aea53aa5765df409929ce1cd74cf232efa4e16e9675dc0b66e846ea37af",
    "anchors": [
      {
        "id": "conflict",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "call",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      },
      {
        "id": "solution",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "place",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 24,
          "endLine": 24
        }
      },
      {
        "id": "backtrack",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      }
    ]
  },
  {
    "documentId": "nQueens.java",
    "language": "java",
    "title": "N 皇后 (Java)",
    "sourceFile": "src/codeCatalog/nQueens/langs/NQueens.java",
    "source": "import java.util.ArrayList;\nimport java.util.Arrays;\nimport java.util.List;\n\n/** N-Queens backtracking — complete Java reference. */\npublic final class NQueens {\n    private final int n;\n    private final int[] cols;\n    private final List<int[]> solutions = new ArrayList<>();\n\n    private NQueens(int n) {\n        this.n = n;\n        this.cols = new int[n];\n        Arrays.fill(cols, -1);\n    }\n\n    public static List<int[]> solveNQueens(int n) {\n        NQueens s = new NQueens(n);\n        s.dfs(0);\n        return s.solutions;\n    }\n\n    private boolean isSafe(int row, int col) {\n        for (int r = 0; r < row; r++) {\n            int c = cols[r];\n            if (c == col || Math.abs(c - col) == row - r) return false;\n        }\n        return true;\n    }\n\n    private void dfs(int row) {\n        if (row == n) {\n            solutions.add(cols.clone());\n            return;\n        }\n        for (int col = 0; col < n; col++) {\n            if (!isSafe(row, col)) continue;\n            cols[row] = col;\n            dfs(row + 1);\n            cols[row] = -1;\n        }\n    }\n}\n",
    "sourceHash": "fd808361f2fa37f22e97716ae136b3917a32397cab3f673e34366a2082557480",
    "anchors": [
      {
        "id": "done",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "conflict",
        "range": {
          "startLine": 26,
          "endLine": 26
        }
      },
      {
        "id": "call",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "solution",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "place",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 39,
          "endLine": 39
        }
      },
      {
        "id": "backtrack",
        "range": {
          "startLine": 40,
          "endLine": 40
        }
      }
    ]
  },
  {
    "documentId": "nQueens.rs",
    "language": "rust",
    "title": "N 皇后 (Rust)",
    "sourceFile": "src/codeCatalog/nQueens/langs/n_queens.rs",
    "source": "/// N-Queens backtracking — complete Rust reference.\npub fn solve_n_queens(n: usize) -> Vec<Vec<i32>> {\n    fn is_safe(cols: &[i32], row: usize, col: i32) -> bool {\n        for r in 0..row {\n            let c = cols[r];\n            if c == col || (c - col).abs() == (row - r) as i32 {\n                return false;\n            }\n        }\n        true\n    }\n    fn dfs(row: usize, n: usize, cols: &mut Vec<i32>, solutions: &mut Vec<Vec<i32>>) {\n        if row == n {\n            solutions.push(cols.clone());\n            return;\n        }\n        for col in 0..n as i32 {\n            if !is_safe(cols, row, col) {\n                continue;\n            }\n            cols[row] = col;\n            dfs(row + 1, n, cols, solutions);\n            cols[row] = -1;\n        }\n    }\n    let mut solutions: Vec<Vec<i32>> = Vec::new();\n    let mut cols = vec![-1; n];\n    dfs(0, n, &mut cols, &mut solutions);\n    solutions\n}\n",
    "sourceHash": "1ba17439b8f96190d4131e941f5cff5106e63a28884cee0e9dc88a8f695e3ae1",
    "anchors": [
      {
        "id": "conflict",
        "range": {
          "startLine": 6,
          "endLine": 7
        }
      },
      {
        "id": "call",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "solution",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "place",
        "range": {
          "startLine": 21,
          "endLine": 21
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "backtrack",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      }
    ]
  },
  {
    "documentId": "nQueens.go",
    "language": "go",
    "title": "N 皇后 (Go)",
    "sourceFile": "src/codeCatalog/nQueens/langs/n_queens.go",
    "source": "package algorithms\n\n// solveNQueens — N-Queens backtracking, complete Go reference.\nfunc solveNQueens(n int) [][]int {\n\tsolutions := [][]int{}\n\tcols := make([]int, n)\n\tfor k := range cols {\n\t\tcols[k] = -1\n\t}\n\tisSafe := func(row, col int) bool {\n\t\tfor r := 0; r < row; r++ {\n\t\t\tc := cols[r]\n\t\t\tif c == col || abs(c-col) == row-r {\n\t\t\t\treturn false\n\t\t\t}\n\t\t}\n\t\treturn true\n\t}\n\tvar dfs func(row int)\n\tdfs = func(row int) {\n\t\tif row == n {\n\t\t\tsolutions = append(solutions, append([]int(nil), cols...))\n\t\t\treturn\n\t\t}\n\t\tfor col := 0; col < n; col++ {\n\t\t\tif !isSafe(row, col) {\n\t\t\t\tcontinue\n\t\t\t}\n\t\t\tcols[row] = col\n\t\t\tdfs(row + 1)\n\t\t\tcols[row] = -1\n\t\t}\n\t}\n\tdfs(0)\n\treturn solutions\n}\n\nfunc abs(x int) int {\n\tif x < 0 {\n\t\treturn -x\n\t}\n\treturn x\n}\n",
    "sourceHash": "faddaeeb140a2345b8a18e460999efba777cbb3546aebdfdf012551303c7568f",
    "anchors": [
      {
        "id": "conflict",
        "range": {
          "startLine": 13,
          "endLine": 14
        }
      },
      {
        "id": "call",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "solution",
        "range": {
          "startLine": 22,
          "endLine": 22
        }
      },
      {
        "id": "place",
        "range": {
          "startLine": 29,
          "endLine": 29
        }
      },
      {
        "id": "recurse",
        "range": {
          "startLine": 30,
          "endLine": 30
        }
      },
      {
        "id": "backtrack",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      }
    ]
  }
]

export default docs
