// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/branchAndBound/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.branchAndBound.py",
    "language": "python",
    "title": "0-1 背包分支限界 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/branchAndBound/langs/knapsack_branch_and_bound.py",
    "source": "def knapsack_branch_and_bound(weights: list[int], values: list[int], W: int) -> int:\n    \"\"\"0-1 knapsack branch-and-bound (density bound) — complete Python reference.\"\"\"\n    n = len(weights)\n    order = sorted(range(n), key=lambda i: -values[i] / weights[i])\n    best = 0\n\n    def bound(i: int, rem_w: int, cur: float) -> float:\n        b = cur\n        w = rem_w\n        for k in range(i, n):\n            idx = order[k]\n            if weights[idx] <= w:\n                w -= weights[idx]\n                b += values[idx]\n            else:\n                b += values[idx] / weights[idx] * w\n                break\n        return b\n\n    def dfs(i: int, rem_w: int, cur: int) -> None:\n        nonlocal best\n        if i == n:\n            if cur > best:\n                best = cur\n            return\n        if bound(i, rem_w, cur) <= best:\n            return\n        idx = order[i]\n        if weights[idx] <= rem_w:\n            dfs(i + 1, rem_w - weights[idx], cur + values[idx])\n        dfs(i + 1, rem_w, cur)\n\n    dfs(0, W, 0)\n    return best\n",
    "sourceHash": "c5231f04aecb481a297306e15881966a84d9c371d2357c761e4bc1968bdb6d38",
    "anchors": [
      {
        "id": "bound",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "prune",
        "range": {
          "startLine": 26,
          "endLine": 27
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 29,
          "endLine": 30
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 31,
          "endLine": 31
        }
      }
    ]
  },
  {
    "documentId": "knapsack.branchAndBound.cpp",
    "language": "cpp",
    "title": "0-1 背包分支限界 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/branchAndBound/langs/knapsack_branch_and_bound.cpp",
    "source": "// 0-1 knapsack branch-and-bound (density bound) — complete C++17 reference.\n#include <algorithm>\n#include <functional>\n#include <numeric>\n#include <vector>\n\nlong long knapsackBranchAndBound(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    int n = static_cast<int>(weights.size());\n    std::vector<int> order(n);\n    std::iota(order.begin(), order.end(), 0);\n    std::stable_sort(order.begin(), order.end(), [&](int a, int b) { return 1.0 * values[a] / weights[a] > 1.0 * values[b] / weights[b]; });\n    long long best = 0;\n    auto bound = [&](int i, int remW, long long cur) -> double {\n        double b = cur;\n        int w = remW;\n        for (int k = i; k < n; k++) {\n            int idx = order[k];\n            if (weights[idx] <= w) {\n                w -= weights[idx];\n                b += values[idx];\n            } else {\n                b += 1.0 * values[idx] / weights[idx] * w;\n                break;\n            }\n        }\n        return b;\n    };\n    std::function<void(int, int, long long)> dfs = [&](int i, int remW, long long cur) {\n        if (i == n) {\n            if (cur > best) best = cur;\n            return;\n        }\n        if (bound(i, remW, cur) <= best) return;\n        int idx = order[i];\n        if (weights[idx] <= remW) dfs(i + 1, remW - weights[idx], cur + values[idx]);\n        dfs(i + 1, remW, cur);\n    };\n    dfs(0, W, 0);\n    return best;\n}\n",
    "sourceHash": "5540c60775acb3391db41de01855e2dd99a2045e1f755be901d5c01c1eea7542",
    "anchors": [
      {
        "id": "bound",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      },
      {
        "id": "prune",
        "range": {
          "startLine": 33,
          "endLine": 33
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 35,
          "endLine": 35
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 36,
          "endLine": 36
        }
      }
    ]
  },
  {
    "documentId": "knapsack.branchAndBound.java",
    "language": "java",
    "title": "0-1 背包分支限界 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/branchAndBound/langs/KnapsackBranchAndBound.java",
    "source": "import java.util.ArrayList;\nimport java.util.Comparator;\nimport java.util.List;\n\n/** 0-1 knapsack branch-and-bound (density bound) — complete Java reference. */\npublic final class KnapsackBranchAndBound {\n    private final int[] weights;\n    private final long[] values;\n    private final int n;\n    private final List<Integer> order = new ArrayList<>();\n    private long best = 0;\n\n    private KnapsackBranchAndBound(int[] weights, long[] values) {\n        this.weights = weights;\n        this.values = values;\n        this.n = weights.length;\n        for (int i = 0; i < n; i++) order.add(i);\n        order.sort(Comparator.comparingDouble(i -> -(double) values[i] / weights[i]));\n    }\n\n    public static long knapsackBranchAndBound(int[] weights, long[] values, int W) {\n        KnapsackBranchAndBound s = new KnapsackBranchAndBound(weights, values);\n        s.dfs(0, W, 0);\n        return s.best;\n    }\n\n    private double bound(int i, int remW, long cur) {\n        double b = cur;\n        int w = remW;\n        for (int k = i; k < n; k++) {\n            int idx = order.get(k);\n            if (weights[idx] <= w) {\n                w -= weights[idx];\n                b += values[idx];\n            } else {\n                b += (double) values[idx] / weights[idx] * w;\n                break;\n            }\n        }\n        return b;\n    }\n\n    private void dfs(int i, int remW, long cur) {\n        if (i == n) {\n            if (cur > best) best = cur;\n            return;\n        }\n        if (bound(i, remW, cur) <= best) return;\n        int idx = order.get(i);\n        if (weights[idx] <= remW) dfs(i + 1, remW - weights[idx], cur + values[idx]);\n        dfs(i + 1, remW, cur);\n    }\n}\n",
    "sourceHash": "80e84e8a4598e04244812d9b8b33ea2367e6073a3a547a467a11d7f354c8f377",
    "anchors": [
      {
        "id": "bound",
        "range": {
          "startLine": 27,
          "endLine": 27
        }
      },
      {
        "id": "prune",
        "range": {
          "startLine": 48,
          "endLine": 48
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 50,
          "endLine": 50
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 51,
          "endLine": 51
        }
      }
    ]
  },
  {
    "documentId": "knapsack.branchAndBound.rs",
    "language": "rust",
    "title": "0-1 背包分支限界 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/branchAndBound/langs/knapsack_branch_and_bound.rs",
    "source": "/// 0-1 knapsack branch-and-bound (density bound) — complete Rust reference (capacity W is `cap`).\npub fn knapsack_branch_and_bound(weights: &[usize], values: &[i64], cap: usize) -> i64 {\n    struct Ctx<'a> {\n        weights: &'a [usize],\n        values: &'a [i64],\n        order: Vec<usize>,\n        best: i64,\n    }\n    fn bound(c: &Ctx, i: usize, rem_w: usize, cur: i64) -> f64 {\n        let mut b = cur as f64;\n        let mut w = rem_w;\n        for k in i..c.order.len() {\n            let idx = c.order[k];\n            if c.weights[idx] <= w {\n                w -= c.weights[idx];\n                b += c.values[idx] as f64;\n            } else {\n                b += c.values[idx] as f64 / c.weights[idx] as f64 * w as f64;\n                break;\n            }\n        }\n        b\n    }\n    fn dfs(c: &mut Ctx, i: usize, rem_w: usize, cur: i64) {\n        if i == c.order.len() {\n            if cur > c.best {\n                c.best = cur;\n            }\n            return;\n        }\n        if bound(c, i, rem_w, cur) <= c.best as f64 {\n            return;\n        }\n        let idx = c.order[i];\n        if c.weights[idx] <= rem_w {\n            dfs(c, i + 1, rem_w - c.weights[idx], cur + c.values[idx]);\n        }\n        dfs(c, i + 1, rem_w, cur);\n    }\n    let density = |i: usize| values[i] as f64 / weights[i] as f64;\n    let mut order: Vec<usize> = (0..weights.len()).collect();\n    order.sort_by(|&a, &b| density(b).total_cmp(&density(a)));\n    let mut c = Ctx { weights, values, order, best: 0 };\n    dfs(&mut c, 0, cap, 0);\n    c.best\n}\n",
    "sourceHash": "0bf2dc3feb3646567d6cf6bbda09389363b4ce7a51669ebce37f4a81cbdd9a74",
    "anchors": [
      {
        "id": "bound",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "prune",
        "range": {
          "startLine": 31,
          "endLine": 32
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 35,
          "endLine": 36
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 38,
          "endLine": 38
        }
      }
    ]
  },
  {
    "documentId": "knapsack.branchAndBound.go",
    "language": "go",
    "title": "0-1 背包分支限界 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/branchAndBound/langs/knapsack_branch_and_bound.go",
    "source": "package algorithms\n\nimport \"sort\"\n\n// knapsackBranchAndBound — 0-1 knapsack branch-and-bound (density bound), complete Go reference.\nfunc knapsackBranchAndBound(weights, values []int, W int) int {\n\tn := len(weights)\n\torder := make([]int, n)\n\tfor i := range order {\n\t\torder[i] = i\n\t}\n\tdensity := func(i int) float64 { return float64(values[i]) / float64(weights[i]) }\n\tsort.SliceStable(order, func(a, b int) bool { return density(order[a]) > density(order[b]) })\n\tbest := 0\n\tbound := func(i, remW, cur int) float64 {\n\t\tb := float64(cur)\n\t\tw := remW\n\t\tfor k := i; k < n; k++ {\n\t\t\tidx := order[k]\n\t\t\tif weights[idx] <= w {\n\t\t\t\tw -= weights[idx]\n\t\t\t\tb += float64(values[idx])\n\t\t\t} else {\n\t\t\t\tb += density(idx) * float64(w)\n\t\t\t\tbreak\n\t\t\t}\n\t\t}\n\t\treturn b\n\t}\n\tvar dfs func(i, remW, cur int)\n\tdfs = func(i, remW, cur int) {\n\t\tif i == n {\n\t\t\tif cur > best {\n\t\t\t\tbest = cur\n\t\t\t}\n\t\t\treturn\n\t\t}\n\t\tif bound(i, remW, cur) <= float64(best) {\n\t\t\treturn\n\t\t}\n\t\tidx := order[i]\n\t\tif weights[idx] <= remW {\n\t\t\tdfs(i+1, remW-weights[idx], cur+values[idx])\n\t\t}\n\t\tdfs(i+1, remW, cur)\n\t}\n\tdfs(0, W, 0)\n\treturn best\n}\n",
    "sourceHash": "5c06311e4b6531f2460da3e47fca98ab38e1ca532251b8216b30c433dc0047be",
    "anchors": [
      {
        "id": "bound",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "prune",
        "range": {
          "startLine": 38,
          "endLine": 39
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 42,
          "endLine": 43
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 45,
          "endLine": 45
        }
      }
    ]
  }
]

export default docs
