// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/bubbleSort/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "bubbleSort.py",
    "language": "python",
    "title": "冒泡排序 (Python)",
    "sourceFile": "src/codeCatalog/bubbleSort/langs/bubble_sort.py",
    "source": "def bubble_sort(a: list[int]) -> list[int]:\n    \"\"\"Bubble sort — complete Python reference.\"\"\"\n    arr = list(a)\n    n = len(arr)\n    for i in range(n - 1):\n        for j in range(n - 1 - i):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr\n",
    "sourceHash": "f9172f3eb60a9e23f8539ea80ab5d03b06a36fee0f4390bbede8982ccaebc296",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      }
    ]
  },
  {
    "documentId": "bubbleSort.cpp",
    "language": "cpp",
    "title": "冒泡排序 (C++)",
    "sourceFile": "src/codeCatalog/bubbleSort/langs/bubble_sort.cpp",
    "source": "// Bubble sort — complete C++17 reference.\n#include <vector>\n\nstd::vector<int> bubbleSort(std::vector<int> arr) {\n    int n = static_cast<int>(arr.size());\n    for (int i = 0; i < n - 1; i++) {\n        for (int j = 0; j < n - 1 - i; j++) {\n            if (arr[j] > arr[j + 1]) {\n                int t = arr[j];\n                arr[j] = arr[j + 1];\n                arr[j + 1] = t;\n            }\n        }\n    }\n    return arr;\n}\n",
    "sourceHash": "b722d1c0295af39c0958b6a37cc29b30bb0e23b644648c4c18d17a0bc0896947",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 9,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  },
  {
    "documentId": "bubbleSort.java",
    "language": "java",
    "title": "冒泡排序 (Java)",
    "sourceFile": "src/codeCatalog/bubbleSort/langs/BubbleSort.java",
    "source": "/** Bubble sort — complete Java reference. */\npublic final class BubbleSort {\n    public static int[] bubbleSort(int[] a) {\n        int[] arr = a.clone();\n        int n = arr.length;\n        for (int i = 0; i < n - 1; i++) {\n            for (int j = 0; j < n - 1 - i; j++) {\n                if (arr[j] > arr[j + 1]) {\n                    int t = arr[j];\n                    arr[j] = arr[j + 1];\n                    arr[j + 1] = t;\n                }\n            }\n        }\n        return arr;\n    }\n}\n",
    "sourceHash": "8be800eb34491b6526f8fe3f28e8187965480e5c5611300962af3d40e357c6d3",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 6,
          "endLine": 6
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 9,
          "endLine": 11
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 15,
          "endLine": 15
        }
      }
    ]
  },
  {
    "documentId": "bubbleSort.rs",
    "language": "rust",
    "title": "冒泡排序 (Rust)",
    "sourceFile": "src/codeCatalog/bubbleSort/langs/bubble_sort.rs",
    "source": "/// Bubble sort — complete Rust reference.\npub fn bubble_sort(a: &[i64]) -> Vec<i64> {\n    let mut arr = a.to_vec();\n    let n = arr.len();\n    for i in 0..n.saturating_sub(1) {\n        for j in 0..n - 1 - i {\n            if arr[j] > arr[j + 1] {\n                arr.swap(j, j + 1);\n            }\n        }\n    }\n    arr\n}\n",
    "sourceHash": "1461bd4a6e1ac92b9ff13af72d2bfcc4f3a934c8aa9e31608d40d866ed5deca2",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 8,
          "endLine": 8
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      }
    ]
  },
  {
    "documentId": "bubbleSort.go",
    "language": "go",
    "title": "冒泡排序 (Go)",
    "sourceFile": "src/codeCatalog/bubbleSort/langs/bubble_sort.go",
    "source": "package algorithms\n\n// bubbleSort — complete Go reference.\nfunc bubbleSort(a []int) []int {\n\tarr := append([]int(nil), a...)\n\tn := len(arr)\n\tfor i := 0; i < n-1; i++ {\n\t\tfor j := 0; j < n-1-i; j++ {\n\t\t\tif arr[j] > arr[j+1] {\n\t\t\t\tarr[j], arr[j+1] = arr[j+1], arr[j]\n\t\t\t}\n\t\t}\n\t}\n\treturn arr\n}\n",
    "sourceHash": "2a2cca828e9e2f8538f20bc60dc46adec015d9b916ff1d9cbe5df20f90632eb2",
    "anchors": [
      {
        "id": "init",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "compare",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "swap",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "done",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "return",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  }
]

export default docs
