// AUTO-GENERATED by scripts/gen-code-langs.mjs from src/codeCatalog/knapsack/backtracking/langs/* — do not edit.
// Each document's line numbers are its own (anchors were written on the statements themselves).
import type { GeneratedLangDoc } from '../../languages'

const docs: GeneratedLangDoc[] = [
  {
    "documentId": "knapsack.backtracking.py",
    "language": "python",
    "title": "0-1 背包回溯 (Python)",
    "sourceFile": "src/codeCatalog/knapsack/backtracking/langs/knapsack_backtracking.py",
    "source": "def knapsack_backtracking(weights: list[int], values: list[int], W: int) -> int:\n    \"\"\"0-1 knapsack backtracking — complete Python reference.\"\"\"\n    best = 0\n\n    def dfs(i: int, rem_w: int, cur: int) -> None:\n        nonlocal best\n        if i == len(weights):\n            if cur > best:\n                best = cur\n            return\n        dfs(i + 1, rem_w, cur)\n        if weights[i] <= rem_w:\n            dfs(i + 1, rem_w - weights[i], cur + values[i])\n\n    dfs(0, W, 0)\n    return best\n",
    "sourceHash": "e8613753dedccf6f7f8c10d0c64221d2de5dff0c3ff23128cbabc9e74f09cd8d",
    "anchors": [
      {
        "id": "call",
        "range": {
          "startLine": 5,
          "endLine": 5
        }
      },
      {
        "id": "best",
        "range": {
          "startLine": 8,
          "endLine": 9
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 11,
          "endLine": 11
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 13,
          "endLine": 13
        }
      }
    ]
  },
  {
    "documentId": "knapsack.backtracking.cpp",
    "language": "cpp",
    "title": "0-1 背包回溯 (C++)",
    "sourceFile": "src/codeCatalog/knapsack/backtracking/langs/knapsack_backtracking.cpp",
    "source": "// 0-1 knapsack backtracking — complete C++17 reference.\n#include <functional>\n#include <vector>\n\nlong long knapsackBacktracking(const std::vector<int>& weights, const std::vector<long long>& values, int W) {\n    long long best = 0;\n    std::function<void(size_t, int, long long)> dfs = [&](size_t i, int remW, long long cur) {\n        if (i == weights.size()) {\n            if (cur > best) best = cur;\n            return;\n        }\n        dfs(i + 1, remW, cur);\n        if (weights[i] <= remW) {\n            dfs(i + 1, remW - weights[i], cur + values[i]);\n        }\n    };\n    dfs(0, W, 0);\n    return best;\n}\n",
    "sourceHash": "434afd531c0f941a5d2b1d8b65d9ca11cd7764566b8b2ffccb8dae548cbee200",
    "anchors": [
      {
        "id": "call",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "best",
        "range": {
          "startLine": 9,
          "endLine": 9
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      }
    ]
  },
  {
    "documentId": "knapsack.backtracking.java",
    "language": "java",
    "title": "0-1 背包回溯 (Java)",
    "sourceFile": "src/codeCatalog/knapsack/backtracking/langs/KnapsackBacktracking.java",
    "source": "/** 0-1 knapsack backtracking — complete Java reference. */\npublic final class KnapsackBacktracking {\n    private final int[] weights;\n    private final long[] values;\n    private long best = 0;\n\n    private KnapsackBacktracking(int[] weights, long[] values) {\n        this.weights = weights;\n        this.values = values;\n    }\n\n    public static long knapsackBacktracking(int[] weights, long[] values, int W) {\n        KnapsackBacktracking s = new KnapsackBacktracking(weights, values);\n        s.dfs(0, W, 0);\n        return s.best;\n    }\n\n    private void dfs(int i, int remW, long cur) {\n        if (i == weights.length) {\n            if (cur > best) best = cur;\n            return;\n        }\n        dfs(i + 1, remW, cur);\n        if (weights[i] <= remW) {\n            dfs(i + 1, remW - weights[i], cur + values[i]);\n        }\n    }\n}\n",
    "sourceHash": "2fb3e5a3e026c60546d7a64e959dc2fc80266165bd13f928e08a45735c6e0caf",
    "anchors": [
      {
        "id": "call",
        "range": {
          "startLine": 18,
          "endLine": 18
        }
      },
      {
        "id": "best",
        "range": {
          "startLine": 20,
          "endLine": 20
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 23,
          "endLine": 23
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 25,
          "endLine": 25
        }
      }
    ]
  },
  {
    "documentId": "knapsack.backtracking.rs",
    "language": "rust",
    "title": "0-1 背包回溯 (Rust)",
    "sourceFile": "src/codeCatalog/knapsack/backtracking/langs/knapsack_backtracking.rs",
    "source": "/// 0-1 knapsack backtracking — complete Rust reference (capacity W is `cap`).\npub fn knapsack_backtracking(weights: &[usize], values: &[i64], cap: usize) -> i64 {\n    fn dfs(i: usize, rem_w: usize, cur: i64, weights: &[usize], values: &[i64], best: &mut i64) {\n        if i == weights.len() {\n            if cur > *best {\n                *best = cur;\n            }\n            return;\n        }\n        dfs(i + 1, rem_w, cur, weights, values, best);\n        if weights[i] <= rem_w {\n            dfs(i + 1, rem_w - weights[i], cur + values[i], weights, values, best);\n        }\n    }\n    let mut best = 0;\n    dfs(0, cap, 0, weights, values, &mut best);\n    best\n}\n",
    "sourceHash": "94d1736411585a351f50a5a607f5d7d85a91a4a30df52e83638d2b1e4bc0da1c",
    "anchors": [
      {
        "id": "call",
        "range": {
          "startLine": 3,
          "endLine": 3
        }
      },
      {
        "id": "best",
        "range": {
          "startLine": 5,
          "endLine": 6
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 10,
          "endLine": 10
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 12,
          "endLine": 12
        }
      }
    ]
  },
  {
    "documentId": "knapsack.backtracking.go",
    "language": "go",
    "title": "0-1 背包回溯 (Go)",
    "sourceFile": "src/codeCatalog/knapsack/backtracking/langs/knapsack_backtracking.go",
    "source": "package algorithms\n\n// knapsackBacktracking — 0-1 knapsack backtracking, complete Go reference.\nfunc knapsackBacktracking(weights, values []int, W int) int {\n\tbest := 0\n\tvar dfs func(i, remW, cur int)\n\tdfs = func(i, remW, cur int) {\n\t\tif i == len(weights) {\n\t\t\tif cur > best {\n\t\t\t\tbest = cur\n\t\t\t}\n\t\t\treturn\n\t\t}\n\t\tdfs(i+1, remW, cur)\n\t\tif weights[i] <= remW {\n\t\t\tdfs(i+1, remW-weights[i], cur+values[i])\n\t\t}\n\t}\n\tdfs(0, W, 0)\n\treturn best\n}\n",
    "sourceHash": "cea801d18af5ab7489ccc60a3fda7c980a59f8992c99781f7d82508055830408",
    "anchors": [
      {
        "id": "call",
        "range": {
          "startLine": 7,
          "endLine": 7
        }
      },
      {
        "id": "best",
        "range": {
          "startLine": 9,
          "endLine": 10
        }
      },
      {
        "id": "skip",
        "range": {
          "startLine": 14,
          "endLine": 14
        }
      },
      {
        "id": "take",
        "range": {
          "startLine": 16,
          "endLine": 16
        }
      }
    ]
  }
]

export default docs
